ministryofjustice/book-a-prison-visit-staff-ui

assets/js/card.js, assets/sass/application.sass, assets/sass/components/_card.scss, integration_tests/pages/index.ts, server/routes/index.test.ts, server/views/components/card/card.njk, server/views/pages/index.njk
Contains some basic tests, although this is a very basic page layout.
=> VB-230: Add initial tiles

server/@types/bapv.d.ts, server/data/prisonApiClient.test.ts, server/data/prisonApiClient.ts, server/data/prisonApiTypes.ts, server/routes/prisoner.test.ts, server/services/prisonerProfileService.test.ts, server/services/prisonerProfileService.ts, server/views/pages/prisoner.njk
Also restricts viewing of offenders to those in Hewell
=> VB-314 Make extra API call to get convicted status on profile page

server/@types/bapv.d.ts, server/data/prisonApiClient.test.ts, server/routes/prisoner.test.ts, server/services/prisonerProfileService.test.ts, server/services/prisonerProfileService.ts
Use simpler method to filter relevant alerts and remove an unnecessary type. Also fix some typos 😳!
=> Simplify filtering alerts and remove FlaggedAlert type

server/routes/testutils/appSetup.ts, server/routes/visitors.test.ts, server/services/prisonerVisitorsService.test.ts, server/services/prisonerVisitorsService.ts, server/views/pages/visitors.njk
* Ensure only **approved** visitors are listed
=> Check visitor 'approved' status & add tests

package-lock.json, package.json, server/routes/testutils/appSetup.ts, server/routes/visitors.test.ts
Fix the session related tests by creating a session object in the test app.
=> VB-332: Fix session tests

server/config.ts
Copied from https://github.com/ministryofjustice/hmpps-template-typescript/pull/69/files
Thought it might be the cause of some of our issues.
=> Sort timeout correctly for HttpAgent

server/@types/bapv.d.ts, server/errorHandler.test.ts, server/routes/index.test.ts, server/routes/prisoner.test.ts, server/routes/search.test.ts, server/routes/testutils/appSetup.ts, server/routes/visitors.test.ts, server/routes/visitors.ts, server/views/pages/additionalSupport.njk, server/views/pages/dateAndTime.test.ts, server/views/pages/index.test.ts, server/views/pages/search.test.ts
Also pre-populates form with session data if available. Some tests skipped while this work in progress.
=> Prevent form re-submission warnings and pre-populate forms with session data (additional support)

server/routes/visitors.test.ts
Check that on successful POSTs, additional requirement choices are saved in session. Slight refactor of tests (and a tidy up) to support this.
=> VB-328: test that additional requirements are stored in session

.eslintrc.json, integration_tests/.eslintrc, package-lock.json, package.json
This was added to the template project recently; been meaning to add it here since I accidentally committed an `.only` test a while ago...
=> Add eslint no-only-tests rule

server/views/pages/dateAndTime.njk
Use Nunjucks macro to remove duplication when generating morning / afternoon slot radio buttons.
=> Refactor date/time slot template to use macro

.circleci/config.yml, Dockerfile, integration_tests/index.d.ts, integration_tests/support/commands.ts
Update re
https://github.com/ministryofjustice/hmpps-template-typescript/pull/74/files
=> Fix docker caching as per template app pull 74

server/routes/search.test.ts, server/routes/search.ts, server/views/pages/index.njk, server/views/pages/index.test.ts, server/views/pages/prisoner.njk, server/views/pages/search/prisoner.njk, server/views/pages/search/prisoner.test.ts, server/views/pages/search/prisonerResults.njk, server/views/partials/searchForPrisonerHeader.njk
May require more rework as I go through this story.
=> VB-639: Refactor search pages

server/@types/bapv.d.ts, server/@types/visit-scheduler-api.d.ts, server/data/visitSchedulerApiClient.test.ts, server/data/visitSchedulerApiClient.ts, server/data/visitSchedulerApiTypes.ts, server/routes/visitorUtils.ts, server/routes/visitors.test.ts, server/routes/visitors.ts, server/services/prisonerProfileService.ts, server/services/visitSessionsService.test.ts, server/services/visitSessionsService.ts, server/views/pages/additionalSupport.njk, server/views/pages/confirmation.njk
Update to work with changed Visit Scheduler API and make naming more consistent.
Add support for passing OPEN / CLOSED visit types - but this is currently hard-coded to 'OPEN'.
=> VB-649: Update to reflect visit scheduler API changes

server/views/pages/search/visit.njk
As requested in ticket by Phoebe Brocket
=> VB-639: Add no visit state to prisoner search link

feature.env, integration_tests/integration/searchByPrisonerFullName.spec.ts, integration_tests/integration/searchForAPrisoner.spec.ts, integration_tests/mockApis/offenderSearch.ts, integration_tests/mockApis/prison.ts, integration_tests/mockApis/prisonerContactRegistry.ts, integration_tests/mockApis/visitScheduler.ts, integration_tests/mockApis/whereabouts.ts, integration_tests/mockApis/wiremock.ts, integration_tests/pages/index.ts, integration_tests/pages/searchForAPrisoner.ts, integration_tests/plugins/index.ts
NOTE: These are likely to change as the tests are written, I just wanted a PR to get all the mocks in place.
=> VB-570: Add mocked endpoints and first page check

server/@types/prisoner-contact-registry.d.ts, server/data/prisonerContactRegistryApiTypes.ts, server/services/prisonerVisitorsService.test.ts, server/services/prisonerVisitorsService.ts, server/services/visitSessionsService.ts, server/utils/visitorUtils.ts, server/views/components/visitors.njk, server/views/pages/visit/summary.njk, server/views/pages/visitors.njk
* update Contact Registry types
* refactor code for building visitors list in `/book-a-visit/select-visitors` to make it more reusable
* add visitor details list to booking summary page
=> VB-680: Visit booking summary page - add visitor details

assets/sass/local.scss, server/routes/visit.ts, server/services/visitSessionsService.ts, server/views/pages/visit/summary.njk
* add any `visitNotes` and additional support requirements to the page
=> VB-680: Visit booking summary - add remaining details

integration_tests/mockApis/visitScheduler.ts, server/data/visitSchedulerApiClient.test.ts, server/middleware/sessionCheckMiddleware.test.ts, server/routes/bookAVisit.test.ts, server/routes/prisoner.test.ts, server/routes/visit.test.ts, server/services/prisonerSearchService.test.ts, server/services/visitSessionsService.test.ts, server/utils/nunjucksSetup.test.ts, server/utils/nunjucksSetup.ts, server/views/components/visitors.test.ts, server/views/pages/prisoner/visits.njk, server/views/pages/search/visitResults.njk, server/views/pages/visit/summary.njk
* Tests relating to the booking summary page
* Updated test data to use valid visit reference characters
* renamed `formatMainContact` Nunjucks filter to `formatLastNameFirst`
=> VB-680 booking summary page tests

server/@types/bapv.d.ts, server/routes/bookAVisit.test.ts, server/routes/bookAVisit.ts, server/routes/visit.test.ts, server/services/prisonerVisitorsService.test.ts, server/services/visitSessionsService.test.ts, server/utils/visitorUtils.ts
Removed `selected` as no longer used - this data now passed via `req.flash`.
=> Tidy VisitorListItem type

server/@types/visit-scheduler-api.d.ts, server/data/visitSchedulerApiClient.test.ts, server/routes/visit.test.ts, server/services/visitSessionsService.test.ts
* Pull in latest visit scheduler types (just adds a `modifiedTimestamp` field to `Visit`) and update test data
=> Update visit scheduler types

assets/sass/local.scss, server/routes/visit.test.ts, server/routes/visit.ts, server/views/pages/confirmation.njk, server/views/pages/visit/cancelConfirmation.njk
Visit cancellation confirmation page, at `/visit/cancelled`.
=> VB-682: Visit cancellation confirmation page

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
This will break affected environments until all are in sync so we need to merge at appropriate time
=> Correct DNS names for this and dependent services

README.md, helm_deploy/book-a-prison-visit-staff-ui/values.yaml
ensure it matches cert name in namespace specification
=> cert name revision

server/routes/prisoner.ts
=> VB-741: Remove duplication of checking offenderNo

server/routes/bookAVisit.ts, server/routes/search.ts
Use `asyncMiddleware` on routes to improve error handling.
=> Use asyncMiddleware for routes

server/@types/visit-scheduler-api.d.ts, server/constants/visitCancellationReasons.ts, server/data/visitSchedulerApiClient.test.ts, server/routes/visit.test.ts, server/routes/visit.ts, server/services/visitSessionsService.test.ts
Update to latest visit scheduler types and update code and tests to support the new structure for visit outcomes.
=> VB-794: Update to support new visit Outcome mappings

.circleci/config.yml
=> Revert multiplatform builds

server/routes/visits.test.ts, server/routes/visits.ts, server/routes/visitsUtils.test.ts, server/routes/visitsUtils.ts, server/views/pages/visits/summary.njk, server/views/pages/visits/summary.test.ts
`startDate` globally renamed as `selectedDate` for this page since `startDate` is unclear when you are talking about the tabs.
=> VB-748: Add tabs to visit search page

assets/sass/local.scss, server/views/pages/dateAndTime.njk, server/views/pages/dateAndTime.test.ts
Date/time picker:
- Reduce the spacing between lines in the summary to be consistent with design and previous page
- Is there any way to reduce the spacing between elements in the accordion pattern? There is a lot of whitespace which makes the page feel long. This pattern probably needs to be more thoroughly tested (and accessibility tested)
=> VB-633: Update date picker as per ticket

server/@types/visit-scheduler-api.d.ts, server/data/visitSchedulerApiClient.test.ts
Update to reflect `restriction` property being removed from visit sessions.
=> Update visit session types and test data

server/views/pages/checkYourBooking.njk, server/views/pages/confirmation.njk
Character's being escaped when main contact is displayed on page
Safe added to checkYourBooking.njk and confirmation.njk
Added to both version of the output
Names like O'brien Smith will no longer be escaped and display correctly
=> VB-845, Safe function added

server/views/pages/checkYourBooking.njk
need to remove the change link on the visit type
can we make it a 2/3rds column width rather than full width?
Change 'prisoner details' to 'prisoner name'
=> VB-909: Amends to pages as requested

server/errorHandler.test.ts, server/errorHandler.ts, server/views/pages/error.njk
Just makes it look less like the app is broken since the font, tags etc are all wrong.
=> Tidy up error page formatting to stop it looking broken

server/routes/bookAVisit.test.ts, server/routes/index.test.ts, server/routes/index.ts, server/views/pages/dateAndTime.njk, server/views/pages/dateAndTime.test.ts, server/views/pages/visitors.njk, server/views/partials/backToStartButton.njk
* Add a route (`/back-to-start`) that clears the session and redirects to `/`
* Add a Nunjucks component `backToStartButton.njk` that can be included to render a button with this link
* Add button to two journey 'dead-ends', where:
* Prisoner has no approved visitors
* No time/date slots available
=> VB-597: Add return to start button for journey dead-ends

server/routes/bookAVisit.test.ts, server/routes/bookAVisit.ts, server/routes/testutils/appSetup.ts
* fixes an issue where a confirmation SMS would still have been sent if the visit booking **failed**
* add test coverage for this route
=> VB-1026: check booking route - bug fix and tests

server/config.ts, server/data/notificationsApiClient.test.ts, server/data/notificationsApiClient.ts, server/routes/bookAVisit.test.ts, server/routes/bookAVisit.ts, server/services/notificationsService.test.ts, server/services/notificationsService.ts
sendSms changed to sendBookedSms so cancellation sms can be built
NotificationsApiClient - Cancellation notification added, including tests
NotificationService - Cancellation notification added, including tests
Cancellation template added to config.ts
Routes - Book A Visit had to be updated to reflect the changing of name of sendSms
=> VB-1013, still WIP - Client+Service ++ Tests done

README.md, server/routes/bookAVisit.test.ts, server/routes/bookAVisit.ts, server/routes/prisoner.ts, server/routes/search.test.ts, server/routes/search.ts, server/routes/visit.test.ts, server/routes/visit.ts, server/routes/visits.ts, server/services/auditService.test.ts, server/services/auditService.ts, server/views/pages/search/visitResults.njk
* Added new audit events:
* `SEARCHED_VISITS`
* `VIEWED_VISIT_DETAILS`
* `VISIT_RESTRICTION_SELECTED`
* Removed `PAGE_VIEW` as not used and no longer required
* Documented audit events and how to use Application Insights to investigate them
* Minor tidy / bug fixes
=> VB-417:  Add more user audit events

README.md, server/routes/visit.test.ts, server/routes/visit.ts, server/services/auditService.test.ts, server/services/auditService.ts
* Add `prisonerId` and `prisonId` to the `VIEWED_VISIT_DETAILS` audit event
=> VB-417:  Audit tweaks

server/services/auditService.ts
Include audit details to help with debugging
=> VB-417: Add audit event details to SQS log message

server/@types/visit-scheduler-api.d.ts
Reflect changes from https://github.com/ministryofjustice/visit-scheduler/pull/142
=> Updates types for visit scheduler

server/app.ts, server/data/notificationsApiClient.test.ts, server/data/notificationsApiClient.ts, server/routes/bookAVisit.ts, server/routes/testutils/appSetup.ts, server/routes/visit.test.ts, server/routes/visit.ts, server/services/notificationsService.test.ts, server/services/notificationsService.ts
Update: Non-elegant solution, feel I need to work on the 'beforeEach' and 'describe' sections.
Is similar implementation to book a visit but could do with some feedback.
Added Cancellation SMS functionality
Send the visitor an SMS when a visit is cancelled
=> VB-1013, send cancellation SMS

server/routes/bookAVisit.ts, server/services/visitSessionsService.test.ts, server/services/visitSessionsService.ts, server/views/pages/bookAVisit/dateAndTime.njk, server/views/pages/bookAVisit/dateAndTime.test.ts
=> Vb 597 back to manage bugfix

server/routes/visit.test.ts, server/routes/visit.ts
* clear any existing session data (e.g. from an abandoned booking journey) before populating `amendVisitSessionData`
* add test to cover expected values in `amendVisitSessionData`
=> VB-922: Clear session before populating for amend

feature.env, integration_tests/e2e/health.cy.ts, integration_tests/e2e/login.cy.ts, integration_tests/mockApis/auth.ts, integration_tests/mockApis/tokenVerification.ts, integration_tests/mockApis/wiremock.ts
Based on PR to template app: https://github.com/ministryofjustice/hmpps-template-typescript/pull/94
=> Add token verification integration tests

.eslintrc.json, server/data/hmppsAuthClient.ts, server/middleware/authorisationMiddleware.ts, server/services/healthCheck.test.ts, server/services/userService.ts
From template app PR: https://github.com/ministryofjustice/hmpps-template-typescript/pull/95 (Minor "code smell" fixes suggested by Sonar Cloud)
=> Minor code fixes

server/routes/bookAVisit.ts, server/routes/visit.ts, server/routes/visitJourney/additionalSupport.ts, server/views/pages/visit/additionalSupport.njk
Refactor the Additional Support logic, change into a class.
Add in functionality for the class works in the Amend Journey
Tests all pass, current using a copy of previous template, just with different reference on form submit
=> Refactored additional support for update journey

server/@types/express/index.d.ts, server/data/visitSchedulerApiClient.ts, server/routes/testutils/appSetup.ts, server/routes/visit.test.ts, server/routes/visit.ts, server/routes/visitJourney/additionalSupport.ts, server/routes/visitJourney/checkYourBooking.ts, server/routes/visitJourney/confirmation.ts, server/routes/visitJourney/dateAndTime.ts, server/routes/visitJourney/selectVisitors.ts, server/routes/visitJourney/visitType.test.ts, server/routes/visitJourney/visitType.ts, server/routes/visitorUtils.test.ts, server/routes/visitorUtils.ts, server/services/visitSessionsService.ts
Changed the wording (functions and session data names) from amend to update
Consistently use update through the code base, as this is what we show to the user. Will help with legibility and understanding.
=> VB-1011, changed all wording from amend to update

server/routes/bookAVisit.test.ts, server/routes/visit.test.ts, server/routes/visitJourney/dateAndTime.ts, server/services/visitSessionsService.test.ts, server/services/visitSessionsService.ts
For consistency with changes in https://github.com/ministryofjustice/book-a-prison-visit-staff-ui/pull/297
=> VB-1126 Rename 'createVisit' to 'reserveVisit' for consistency

server/routes/visitJourney/selectVisitors.ts, server/views/pages/bookAVisit/additionalSupport.njk, server/views/pages/bookAVisit/dateAndTime.njk, server/views/pages/bookAVisit/mainContact.njk, server/views/pages/bookAVisit/visitType.njk, server/views/pages/bookAVisit/visitors.njk
Back button was defaulting to the visit journey URL's, this PR aim's to use urlPrefix in place of a hardcoded url, so for both journeys the back button navigates the user to the correct page.
urlPrefix is already being used for the form actions, so this is a good re-use of existing code we've implemented.
=> VB-1137, use url prefix in back button

.circleci/config.yml, .husky/pre-commit, package.json
From
```Test Suites: 1 skipped, 42 passed, 42 of 43 total
Tests:       11 skipped, 391 passed, 402 total
Snapshots:   0 total
Time:        23.867 s```
to
```Test Suites: 1 skipped, 42 passed, 42 of 43 total
Tests:       11 skipped, 392 passed, 403 total
Snapshots:   0 total
Time:        4.121 s```
=> Speed up jest

server/views/pages/bookAVisit/confirmation.njk, server/views/partials/backToStartButton.njk
Use same wording for buttons in various places that take user back to the 'home' page. (Arose as part of discussions on VB-1084.)
=> VB-1084: Standardise back to start button text

server/views/pages/visit/summary.njk
Changed the displayed text in the event of a superseded / cancelled visit
=> vb-1172, text changed

docker-compose.yml, server/routes/index.test.ts, server/routes/index.ts, server/views/pages/index.njk, server/views/pages/index.test.ts
see https://mojdt.slack.com/archives/C01DU5U4NMU/p1663080874499769
=> Add Change a visit tile to feature flag

server/routes/bookAVisit.test.ts, server/routes/visit.test.ts, server/routes/visitJourney/selectVisitors.ts
Allow more than two adult visitors to be selected - following discussion on VB-1139.
=> VB-1182: Remove no more than 2 adults limit

server/views/partials/searchForVisitHeader.njk
Added autocomplete off to the search by visit reference field.
Autocomplete off on Edge doesn't have any effect on the main contact page (which this ticket was created for) - so will discuss this in stand up to see if we can agree on a course of action
=> vb-1196, autocomplete added to search for visit, works correctly

server/routes/search.test.ts, server/routes/search.ts, server/services/auditService.test.ts, server/services/auditService.ts
Not really a POC, just the first Audit function to be changed, if we're OK with this then I can do the rest in one PR.
=> VB-1217: Move HEI into Audit function for prisonerSearch

server/routes/visitJourney/confirmation.test.ts, server/views/pages/bookAVisit/confirmation.njk
Updated the information on the Booking Confirmation page (visit details)
Tests updated to include the new (reduced) amount of information
=> Vb 1144 change visit details

assets/sass/local.scss, server/views/components/card/card.njk, server/views/pages/bookAVisit/checkYourBooking.njk, server/views/pages/search/visit.njk
Changed all visited links to default blue, added to top of local.scss and targeted a parent class to make sure it was targeting only the links, not the buttons
=> vb-1181, Remove visited state from all links

server/@types/visit-scheduler-api.d.ts, server/data/visitSchedulerApiClient.test.ts, server/routes/visit.test.ts, server/services/prisonerProfileService.test.ts, server/services/visitSessionsService.test.ts
Update types to take into account new endpoints and changes to DTOs. First step of switching over to use new endpoints.
=> VB-1208: Update visit scheduler types

server/routes/visitJourney/confirmation.test.ts, server/routes/visitJourney/confirmation.ts, server/views/pages/bookAVisit/confirmation.njk
Change the heading and content for the confirmation page, when on the amend journey.
Uses isUpdate (as used on other pages) on page to pick which content to display, and in the tests
=> vb-1084, Update confirmation page for amend journey

server/data/restClient.ts, server/data/visitSchedulerApiClient.test.ts, server/data/visitSchedulerApiClient.ts
Chance cancel endpoint to use the put method.
Remove all patch code, as this is no longer used
=> vb-1230, remove patch throughout, change cancel endpoint

server/routes/visit.ts, server/routes/visitJourney/checkYourBooking.test.ts, server/routes/visitJourney/checkYourBooking.ts, server/routes/visitJourney/dateAndTime.test.ts, server/routes/visitJourney/dateAndTime.ts, server/services/auditService.test.ts, server/services/auditService.ts
also added application reference to the reserve and book calls to the audit service
Updated the audit service to accept application reference when making a booking or reservation
Included application reference in the audit service calls for both reserve and book
=> vb-1236, added application reference to audit service,

server/routes/visitJourney/additionalSupport.test.ts
Additional Support tests now use the journey loop, to run through both the book and amend journeys
=> vb-1024, additional support requests using journey loop

server/routes/visit.test.ts, server/routes/visitJourney/mainContact.test.ts
Unit tests for main contact now test both journeys, also removed tests from visit relating to main contact
Linter pointed out some now unused code, so removed that from visit.test
=> vb-1024, main contact tests updated

server/routes/visitJourney/checkYourBooking.test.ts
Tests for check your booking have been updated.
These changes have been made post endpoint change, so work with the new endpoints and calls
=> vb-1204, check your booking tests updated

server/routes/visitJourney/dateAndTime.ts, server/views/pages/bookAVisit/dateAndTime.njk
Updates restriction change message to account for each different scenario
Only displays during the update journey
Currently no unit tests use/test this code
=> VB-1264, display visit restriction changed message

server/routes/visitJourney/confirmation.test.ts, server/views/pages/bookAVisit/confirmation.njk
Minor update to wording on booking confirmation page when updating a visit.
=> VB-1260: Update confirmation page wording

assets/sass/components/_header-bar.scss, assets/sass/local.scss, server/views/partials/header.njk
Restructured the beta banner section, to stop it sitting offset on the second line, when on a small view
=> VB-1223, changed beta banner to support smaller view

helm_deploy/values-prod.yaml
Turn on the feature flag for update journey for prod so it's ready for upcoming release.
=> VB-1280: Enable update journey in prod

server/utils/azureAppInsights.ts
Use the correct connection string, copied from template app https://github.com/ministryofjustice/hmpps-template-typescript/blob/main/server/utils/azureAppInsights.ts
=> VB-1325: Update AppInsights connection string

cypress.config.ts, feature.env, integration_tests/index.d.ts, integration_tests/mockApis/offenderSearch.ts, integration_tests/mockApis/prison.ts, integration_tests/mockApis/prisonerContactRegistry.ts, integration_tests/mockApis/visitScheduler.ts, integration_tests/mockApis/whereabouts.ts, integration_tests/mockApis/wiremock.ts, server/data/prisonApiClient.test.ts, server/data/prisonerContactRegistryApiClient.test.ts, server/services/visitSessionsService.test.ts
Preparatory work before adding new tests for booking journey:
* tidied Cypress config (make consistent, cleanup following automated migration from v9 to v10)
* mock APIs
* added types
* updated test data to reflect schema changes
* removed deprecated endpoints
=> VB-729: Tidy Cypress config and mocks

server/config.ts, server/routes/index.test.ts, server/routes/index.ts, server/routes/visit.test.ts, server/routes/visit.ts, server/routes/visitJourney/additionalSupport.test.ts, server/routes/visitJourney/checkYourBooking.test.ts, server/routes/visitJourney/confirmation.test.ts, server/routes/visitJourney/dateAndTime.test.ts, server/routes/visitJourney/mainContact.test.ts, server/routes/visitJourney/selectVisitors.test.ts, server/routes/visitJourney/visitType.test.ts, server/views/pages/index.njk, server/views/pages/index.test.ts, server/views/pages/visit/summary.njk
Remove the update journey feature flag
Removed the tests which checked whether it was toggled on/off
Removed the checks on pages which changed displays
=> VB-1292, remove update journey feature flag

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, server/config.ts, server/routes/index.test.ts, server/routes/index.ts, server/routes/visit.test.ts, server/routes/visit.ts, server/routes/visitJourney/additionalSupport.test.ts, server/routes/visitJourney/checkYourBooking.test.ts, server/routes/visitJourney/confirmation.test.ts, server/routes/visitJourney/dateAndTime.test.ts, server/routes/visitJourney/mainContact.test.ts, server/routes/visitJourney/selectVisitors.test.ts, server/routes/visitJourney/visitType.test.ts, server/views/pages/index.njk, server/views/pages/index.test.ts, server/views/pages/visit/summary.njk
Remove the update journey feature flag enabled setting from the deployment YAML files
=> Vb 1292 remove update feature flag

server/app.ts, server/routes/changeEstablishement.ts, server/routes/changeEstablishment.ts, server/routes/testutils/appSetup.ts, server/views/pages/changeEstablishment.njk
Change establishment page created
Added change establishment route
Currently using pre-coded prison list (not using a service) 
Using VB-1390's session variable 'selectedEstablishment' for pre-selection
GET method done, no POST.
First route and page created so would appreciate the input
=> VB-1222, change establishment page created, includes GET method

server/@types/bapv.d.ts, server/@types/express/index.d.ts, server/middleware/populateSelectedEstablishment.test.ts, server/middleware/populateSelectedEstablishment.ts, server/routes/changeEstablishment.ts, server/routes/visit.ts, server/routes/visitJourney/checkYourBooking.ts, server/views/pages/changeEstablishment.njk, server/views/pages/search/prisonerResults.njk, server/views/pages/search/visitResults.njk, server/views/partials/header.njk
Add type for `Prison` - using same property names as https://github.com/ministryofjustice/prison-register for future compatibility. Precursor to adding a `SupportedPrisonsService` into the application.
=> VB-1409: Add type for 'Prison'

server/routes/changeEstablishment.test.ts, server/routes/changeEstablishment.ts, server/views/pages/changeEstablishment.njk
GET and POST both working, change environment variable: selectedEstablishment
GET and POST tests now cover both (un)/happy paths, correctly tests that establishment has changed
Feature flag being used
=> VB-1383, Select Establishment post and tests

assets/sass/local.scss, server/routes/index.test.ts, server/routes/index.ts, server/routes/search.test.ts, server/routes/search.ts, server/views/partials/header.njk
Added change establishment link to Index, search pages and results
Added tests to ensure link only being displayed when feature flag is enabled
=> VB-1400, show change establishment link and tests

assets/sass/local.scss, server/routes/changeEstablishment.test.ts, server/routes/changeEstablishment.ts, server/routes/search.ts, server/utils/utils.test.ts, server/utils/utils.ts, server/views/pages/changeEstablishment.njk, server/views/partials/header.njk
Take request refer as a URL parameter when coming from any of the search pages.
If coming from index or when auto-directed here (VB-1412) then it will redirect back to index 
Currently no referral tests implemented, beyond the regular index.
Really just a PR for input
=> VB-1400, add redirect to change establishment page

assets/sass/local.scss, server/routes/visitJourney/dateAndTime.test.ts, server/routes/visitJourney/dateAndTime.ts, server/views/pages/bookAVisit/dateAndTime.njk
https://dsdmoj.atlassian.net/jira/software/c/projects/VB/boards/598?modal=detail&selectedIssue=VB-1345
=> VB-1345: Add location and rearrange date/time intro

server/data/visitSchedulerApiClient.test.ts, server/data/visitSchedulerApiClient.ts
Use list of supported prison IDs returned from the Visit Scheduler.
=> VB-1409: Use supported prisons list from Visit Scheduler

server/@types/bapv.d.ts, server/@types/visit-scheduler-api.d.ts, server/data/visitSchedulerApiClient.test.ts, server/data/visitSchedulerApiClient.ts, server/routes/prisoner.test.ts, server/routes/prisoner.ts, server/routes/search.test.ts, server/routes/visits.test.ts, server/services/prisonerProfileService.ts, server/services/visitSessionsService.test.ts, server/services/visitSessionsService.ts, server/views/pages/prisoner/visits.njk, server/views/pages/search/visitResults.njk
Display upcoming cancelled visits on booking search and prisoner upcoming visits pages
Removed timestamp from upcomingVisits call.
Faked time on the apiClient test for upcomingVisits
Rebased from main
=> VB-1474, Upcoming visits: show BOOKED and CANCELLED visits

feature.env, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-staging.yaml, server/config.ts, server/middleware/populateSelectedEstablishment.test.ts, server/middleware/populateSelectedEstablishment.ts, server/routes/changeEstablishment.test.ts, server/routes/changeEstablishment.ts, server/routes/index.test.ts, server/routes/index.ts, server/routes/search.test.ts, server/routes/search.ts
Remove establishment switcher feature flag checks.
Also removed the variable from config and helm files
=> VB-1462, Remove establishment switcher feature flag

server/data/__testutils/testObjects.ts, server/routes/prisoner.test.ts, server/services/prisonerProfileService.test.ts
Removed the basic prisoner from the prisoner profile tests, added it into the testObjects file.
This test file still needs more work
=> VB-1540, moved prisoner to test data - prisoner profile tests

server/utils/nunjucksSetup.test.ts, server/utils/nunjucksSetup.ts
DisplayAge's calculation was found to have been giving incorrect ages in certain situations.
Attempted to use Date-FNS (which is already being used in this project), but this also failed some specific situations.
This is a manual method for calculating ages, which works with both Plural and Singular.
It's fiddly and not the easiest to read through, but it works on all tests (some of which were previously found to cause issues with previous iterations of this logic)
Very open to suggestions as this is my own calculation (Not copy pasted)
=> VB-1593, manual age calculation

server/@types/bapv.d.ts, server/data/visitSchedulerApiClient.test.ts, server/data/visitSchedulerApiClient.ts, server/services/prisonerProfileService.test.ts, server/services/prisonerProfileService.ts, server/views/pages/prisoner/profile.njk
Update prisoner profile page to include:
Reference with link to a specific booking
Both booked and cancelled visits are to be shown
=> VB-1463, View details of bookings - prisoner profile page

server/views/pages/bookAVisit/confirmation.njk
Changed new 'Book another visit for this prisoner' button to stacked display
=> VB-1424, stacked book another visit button

server/data/__testutils/testObjects.ts, server/routes/visit.test.ts
Remove visit data from visit.test.ts, moved to testObject file.
=> VB-1540, separate visit into test data object for visit.test

server/routes/visitJourney/selectVisitors.test.ts, server/routes/visitJourney/selectVisitors.ts
Add validation to select visitors page to limit maximum to 10. This is to match the limit imposed by the Visit Scheduler.
=> VB-1704: Limit number of selected visitors to maximum 10

server/views/pages/bookAVisit/dateAndTime.njk, server/views/pages/bookAVisit/dateAndTime.test.ts
Changed the text block for 'What time slots are shown?' section to include 'and incentive level'
Added a test for this section
=> VB-1660 incentive based slot information

server/constants/prisonConfiguration.ts
Added prison specific contact details for Cardiff, Preston and Wandsworth Prisons
Included their capacity's (Used on view visits by date page), although this will be superseded by an upcoming ticket.
=> VB-1674 / VB-1665 / VB-1679 - Prison specific contact details

server/constants/prisonConfiguration.test.ts, server/constants/prisonConfiguration.ts
Removing hard-coded session capacity data now that this is retrieved from the visit scheduler.
=> VB-1740: Remove hard-coded session capacity

integration_tests/mockApis/visitScheduler.ts, server/data/visitSchedulerApiClient.test.ts, server/data/visitSchedulerApiClient.ts, server/data/visitSchedulerApiTypes.ts, server/services/prisonerProfileService.test.ts, server/services/prisonerProfileService.ts, server/services/visitSessionsService.test.ts, server/services/visitSessionsService.ts
Use new GET  /visits/search endpoint for visits
Used on prisoner profile page, view visits by date and search for booking (by prisoner name/number)
=> VB-1760, upcoming and past visits using new endpoint

server/@types/bapv.d.ts, server/routes/visitJourney/dateAndTime.test.ts, server/routes/visitJourney/dateAndTime.ts, server/routes/visitJourney/selectVisitors.test.ts, server/routes/visitJourney/selectVisitors.ts, server/routes/visitJourney/visitType.test.ts, server/routes/visitJourney/visitType.ts, server/views/pages/bookAVisit/dateAndTime.njk, server/views/pages/bookAVisit/dateAndTime.test.ts
Add new message when previous visit slot is no longer available 
(IEP Level change, location change, loss of enhanced)
All previous tests affected have been updates, still needs test for this new message
=> VB-1416 add session conflict message

feature.env, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-staging.yaml, integration_tests/integration/home.cy.ts, integration_tests/pages/home.ts, integration_tests/tsconfig.json, server/config.ts, server/routes/index.ts, server/views/pages/index.njk, server/views/pages/index.test.ts
Added the 'View Timetable' tile to the home page
Added the config to all environments, only enabled in dev.
Updated the integration tests to include testing for the tile.
=> VB-1850, view timetable tile

integration_tests/mockApis/auth.ts, server/app.ts
Ensure user has `ROLE_MANAGE_PRISON_VISITS` in order to access the application.
=> VB-1857: Check user has correct role to access application

server/routes/timetable.test.ts, server/routes/timetable.ts
Default to current day on visit timetable
=> VB-18-41: Default to selecting current day on visit timetable

cypress.config.ts, integration_tests/integration/bookAVisit.cy.ts, integration_tests/integration/prisonerProfile.cy.ts, integration_tests/integration/visitTimetable.cy.ts, integration_tests/mockApis/visitScheduler.ts, integration_tests/pages/page.ts, integration_tests/pages/prisonerProfile.ts, integration_tests/pages/searchForAPrisoner.ts, integration_tests/pages/searchForAPrisonerResults.ts, integration_tests/pages/visitTimetable.ts, server/routes/timetable.test.ts, server/views/pages/timetable.njk
Add integration test for visit timetable. (Plus minor tweaks to handling of back link in existing tests.)
=> VB-1841: View timetable integration test

server/@types/bapv.d.ts, server/routes/visitJourney/selectVisitors.ts
Tidy of some unused code that is no longer needed (probably since #490 )
=> VB-1416: Tidy up unused code

feature.env, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-staging.yaml, server/config.ts, server/routes/index.test.ts, server/routes/index.ts, server/routes/timetable.test.ts, server/routes/timetable.ts, server/views/pages/index.njk
Remove all code related to the feature flag for `View Timetable`
=> VB-1987, remove feature flag code for view timetable

cypress.config.ts, integration_tests/integration/cancelVisit.cy.ts, integration_tests/mockApis/visitScheduler.ts, integration_tests/pages/cancelVisit.ts, integration_tests/pages/visitCancelled.ts
Test the full cancel visit journey with integration tests
=> VB-1883, cancel visit journey integration tests

server/middleware/populateSelectedEstablishment.test.ts, server/middleware/populateSelectedEstablishment.ts, server/routes/changeEstablishment.test.ts
Minor tweaks (mainly to tests) following refactoring work on VB-1430.
=> VB-1430 Minor tweaks following VB-1430 refactor 

package-lock.json, package.json, server/middleware/sessionCheckMiddleware.ts, server/routes/visitJourney/additionalSupport.ts, server/routes/visitJourney/checkYourBooking.ts
Add logging of key details when a request fails session check middleware. The aim is to better understand context when these requests fail.
Also remove some obsolete logging.
=> VB-2004 Add logging to session middleware check

package-lock.json, package.json
The security task flagged outdated node modules, this PR fixes all flagged issues and includes other non-essential dependency updates
=> 11-04-22 / Dependencies updated

integration_tests/integration/bookAVisit.cy.ts, integration_tests/integration/prisonerProfile.cy.ts, server/data/orchestrationApiClient.test.ts, server/routes/testutils/testData.ts, server/services/prisonerProfileService.test.ts
Added new prisonerProfilePage object to test data.
Using new test data object for integration testing and prisonerProfileService tests
Added test in orchestrationApiClient
=> VB-2161, add prisonerProfile test data object and use

server/constants/prisonConfiguration.ts
Text content for prisons that are to be onboarded. Contains text for number of visitors and a phone number to include in SMS cancellation messages.
(First commit sorts existing data alphabetically; second one adds the new content - so probably simpler to just review that as the combined diff makes it look a bit tangled...)
=> VB-2181, VB-2184, VB-2183, VB-2180, VB-2178, VB-2182, VB-2179 Prison onboarding

integration_tests/integration/bookAVisit.cy.ts, server/data/visitSchedulerApiClient.test.ts, server/data/visitSchedulerApiClient.ts, server/routes/prisoner.test.ts, server/routes/prisoner.ts, server/services/prisonerProfileService.ts
Removed unused endpoints from `prisonerProfileService.ts` and `prisoner.ts`
Tests updated to reflect the removal of endpoints
Changed prisoner's POST route to use getProfile instead of old endpoint
Some endpoints remain which may be used temporarily while awaiting further back end changes
=> VB-2161 remove excess endpoints

integration_tests/integration/bookAVisit.cy.ts, integration_tests/integration/checkYourBooking.cy.ts, integration_tests/integration/updateAVisit.cy.ts, integration_tests/mockApis/orchestration.ts, server/@types/orchestration-api.d.ts, server/@types/prison-api.d.ts, server/@types/prisoner-offender-search-api.d.ts, server/@types/whereabouts-api.d.ts, server/data/orchestrationApiClient.test.ts, server/data/orchestrationApiClient.ts
Add sessionTemplateReference to the changeReservedVisit call, as this was found to not being updated so was matching visits to the incorrect visit slots.
=> Vb 2271 update journey session template reference

server/views/pages/bookAVisit/dateAndTime.njk, server/views/pages/bookAVisit/dateAndTime.test.ts
Updated formatting to better match example given in ticket - Fully booked visit session tag date and time page
=> VB-1974, minor formatting irregularity fixed

server/routes/visitJourney/selectVisitors.test.ts, server/routes/visitJourney/selectVisitors.ts, server/views/pages/bookAVisit/visitors.njk
Changed implementation of how visitor checkboxes are disabled
Adult has been set to only True or False, being true in the case that no DOB is present. This was for this PR but was also some old logic which needed to be updated
See comments
=> VB-2376, improve selectVisitors to remove bug

server/views/layout.njk
Add IT Incident hub link to footer, for display on all pages
=> VB-2082, add Incident hub link to footer

integration_tests/integration/visitTimetable.cy.ts, server/@types/orchestration-api.d.ts, server/@types/prison-api.d.ts, server/@types/prison-register-api.d.ts, server/@types/prisoner-contact-registry-api.d.ts, server/@types/prisoner-offender-search-api.d.ts, server/@types/whereabouts-api.d.ts, server/constants/sessionTemplateFrequency.ts, server/routes/testutils/testData.ts, server/routes/timetable.test.ts, server/routes/timetable.ts, server/views/pages/timetable.njk
This reverts commit 4fee644c93492a89e5e384dfc4b3e9f92bcf5f1f.
Re-apply this - onto `develop` branch
=> Revert "Revert "VB-2357 Support n-weekly schedule (#602)" (#605)"

integration_tests/integration/visitTimetable.cy.ts, server/routes/timetable.test.ts, server/views/pages/timetable.njk
On the 'View visits timetable' page, show "One off" for sessions if there is an end date set that matches the session template start date.
=> VB-2357: Handle 'one off' sessions on timetable

cypress.config.ts, integration_tests/integration/bookAVisit.cy.ts, integration_tests/integration/cancelVisit.cy.ts, integration_tests/integration/checkYourBooking.cy.ts, integration_tests/integration/updateAVisit.cy.ts, integration_tests/integration/visitDetails.cy.ts, integration_tests/mockApis/orchestration.ts, integration_tests/pages/visitDetails.ts, server/@types/orchestration-api.d.ts, server/@types/prison-api.d.ts, server/@types/prison-register-api.d.ts, server/@types/prisoner-contact-registry-api.d.ts, server/@types/prisoner-offender-search-api.d.ts, server/@types/whereabouts-api.d.ts, server/data/orchestrationApiClient.test.ts, server/data/orchestrationApiClient.ts, server/data/orchestrationApiTypes.ts, server/routes/testutils/testData.ts, server/routes/visit.test.ts, server/routes/visit.ts, server/routes/visitJourney/checkYourBooking.ts, server/services/visitService.test.ts, server/services/visitService.ts, server/views/pages/visit/summary.njk
Incorporate API changes for Cost of our service into VSiP, this PR looks to make all journeys functional under these new API's, future PR's will look to add the relevant page and display that information.
Minor note: will need a constants file to display the 'human readable' version of the event history type (currently displays 'BOOKED_VISIT / MIGRATED_VISIT,' instead of Visit booked / Visit migrated, on the booking summary page, next to the time, date, and name of when the action was made
=> VB-2540, incorporate api changes into project

server/routes/changeEstablishment.test.ts, server/routes/changeEstablishment.ts
Sort establishment list by prison name, instead of prison code.
=> VB-2574 Sort establishment list by prison name

package-lock.json, package.json
Security issues are still not addressable
Minor non-breaking packages update
=> Package updates - 09-08-2023

server/constants/eventAuditTypes.ts, server/views/pages/visit/summary.njk
Show 'Visit migrated' against the migrated visit events on the visit summary page
=> VB-2671, display migrated visit against migrated events

integration_tests/integration/visitDetails.cy.ts, integration_tests/pages/visitDetails.ts, server/constants/requestMethods.ts, server/routes/visit.test.ts, server/routes/visit.ts, server/views/components/visitors.njk, server/views/components/visitors.test.ts, server/views/pages/bookAVisit/visitors.njk, server/views/pages/visit/summary.njk
Added sub navigation and tabs to prisoner profile page
`govuktimeline` macro wouldn't work so manually built using the example classes
=> VB-1848, Add tabs view on visit details page

server/constants/prisonConfiguration.ts
* Fix for Werrington
* Update prison specific config for onboarding.
=> VB-2701, VB-2599, VB-2611, VB-2682, VB-2625, VB-2663, VB-2633 Update prison config

server/views/layout.njk, server/views/partials/header.njk, server/views/partials/searchForVisitHeader.njk
Add role to backlink and location bar
Add labels to visit reference search page
=> Minor accessibility fixes

server/routes/visit.test.ts, server/routes/visit.ts, server/views/pages/visit/summary.njk
Separate cancel/update button show logic
Cancel button displays up to 28 days after the visit start time
=> VB-2694, show cancel button if less than 28 days after visit start time

server/@types/orchestration-api.d.ts, server/@types/prison-api.d.ts, server/@types/prison-register-api.d.ts, server/@types/prisoner-contact-registry-api.d.ts, server/@types/prisoner-offender-search-api.d.ts, server/@types/whereabouts-api.d.ts, server/routes/testutils/testData.ts
Update types from Orchestration service and prison api etc
One small change from Orchestration service, just required test data to be changed as it no longer matched on type
=> 27/09/2023 - update types from orchestration and prison api etc

integration_tests/pages/requestMethod.ts, server/@types/orchestration-api.d.ts, server/@types/prison-api.d.ts, server/@types/prisoner-offender-search-api.d.ts, server/@types/whereabouts-api.d.ts, server/constants/requestMethods.ts, server/routes/visit.test.ts, server/routes/visit.ts, server/routes/visitJourney/checkYourBooking.ts, server/routes/visitJourney/requestMethod.test.ts, server/routes/visitJourney/requestMethod.ts, server/views/pages/bookAVisit/requestMethod.njk, server/views/pages/visit/cancel.njk
* Support new "By the prisoner" request method option in the booking journey
* This **is not** included in the list of request methods when cancelling a visit
=> VB-3195 Update request methods to include applications made by a prisoner

server/@types/orchestration-api.d.ts, server/@types/prison-api.d.ts, server/@types/prisoner-offender-search-api.d.ts
Import new types (required for knowing the PrisonDTO definition which is used in VB-3200)
=> VB-3200-update-type-definition

assets/js/filter-component.js, assets/sass/application.scss, assets/sass/components/_filter.scss, integration_tests/integration/review.cy.ts, integration_tests/pages/visitsReviewListing.ts, server/@types/bapv.d.ts, server/routes/review/index.ts, server/routes/review/visitsReviewListingController.test.ts, server/routes/review/visitsReviewListingController.ts, server/services/visitNotificationsService.test.ts, server/services/visitNotificationsService.ts, server/views/components/filter/macro.njk, server/views/components/filter/template.njk, server/views/pages/review/visitsReviewListing.njk
Add filter component for the bookings to review listing page. Filter by user name, reason for review - or both.
(Bulk of the filter template and JS/SCSS taken from the https://github.com/ministryofjustice/prepare-a-case repo - with minor customisations.)
###  Selecting filters
=> VB-3239 Filter component for bookings to be reviewed listing

integration_tests/integration/review.cy.ts, integration_tests/integration/visitDetails.cy.ts, integration_tests/pages/visitDetails.ts, server/constants/eventAuditTypes.ts, server/constants/notificationEvents.ts, server/routes/review/visitsReviewListingController.test.ts, server/routes/review/visitsReviewListingController.ts, server/routes/visit.test.ts, server/routes/visit.ts, server/services/visitNotificationsService.ts, server/views/pages/visit/summary.njk
Change how the information is displayed for cancellations
=> VB-3355 change display on timeline

helm_deploy/values-prod.yaml
Reverts ministryofjustice/book-a-prison-visit-staff-ui#712
=> Revert "VB-3015 Enable proactive bookings review in prod"

helm_deploy/values-prod.yaml
Reverts ministryofjustice/book-a-prison-visit-staff-ui#714
=> Revert "Revert "VB-3015 Enable proactive bookings review in prod""

integration_tests/integration/visitDetails.cy.ts, server/routes/visit.test.ts, server/views/pages/visit/summary.njk
Add date of week to Visit booking details page
=> Added day of week to visit details page

integration_tests/integration/searchForABooking.cy.ts, integration_tests/mockApis/orchestration.ts, server/data/orchestrationApiClient.test.ts, server/data/orchestrationApiClient.ts, server/routes/prisoner.test.ts, server/routes/prisoner.ts, server/services/visitService.test.ts, server/services/visitService.ts
Use the new API provided by the orchestration service for receiving future visits on the search page
=> VB-3473, new api for future visits

helm_deploy/values-staging.yaml
Reverts ministryofjustice/book-a-prison-visit-staff-ui#708
=> Revert "Update values-staging.yaml" - remove User Vision access

server/routes/visitJourney/mainContact.test.ts, server/routes/visitJourney/mainContact.ts, server/views/pages/bookAVisit/mainContact.njk
Bugfix
Show error message if neither radio option is selected for phone number (main contact page)
=> VB-3415 Show error message if no phone number option selected

server/routes/visitJourney/additionalSupport.test.ts, server/routes/visitJourney/additionalSupport.ts, server/views/pages/bookAVisit/additionalSupport.njk
Add application reference to a data-test attribute on additional support page 'continue' button
=> Add application reference to data-test on additional support page

server/views/pages/timetable.njk
Change advice regarding timetable changes
=> VB-3586, change view visits timetable page content

feature.env, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-staging.yaml, server/config.ts, server/constants/eventAuditTypes.ts, server/constants/visitCancellationReasons.test.ts, server/constants/visitCancellationReasons.ts, server/routes/index.test.ts, server/routes/index.ts, server/routes/review/index.ts, server/routes/review/visitsReviewListingController.test.ts, server/routes/visit.test.ts, server/routes/visit.ts, server/services/visitService.test.ts, server/services/visitService.ts, server/views/pages/index.njk
Remove all feature flag code for the 'Proactive booking' feature
=> VB-3450, remove proactive bookings feature flag

server/constants/prisonConfiguration.ts
Updated Preston visitor allowance information
=> VB-3653 Update adult and child limits for Preston (PNI)

server/constants/prisonConfiguration.ts
Minor change to reflect new visitor numbers for Send (SDI)
=> Update Send SDI visitor allowances

integration_tests/integration/prisonerProfile.cy.ts, server/routes/prisoner.test.ts, server/views/pages/prisoner/profile.njk
Add day of week to the date for each visit on prisoner profile page
=> VB-3756, add day of week to prisoner profile-visits

server/constants/prisonConfiguration.ts
Added Whitemoor (HMP) / WRI to the prison Config file with details on the visitor rules.
=> VB-3677 Added WRI to prisonConfiguration.ts

server/constants/prisonConfiguration.ts
=> Update DMI prisonConfiguration.ts

server/constants/prisonConfiguration.ts, server/routes/visitJourney/selectVisitors.test.ts
Added BFI visitor allowance config and tided wording for other prisons.
This needs to go live on 13/05/24.
=> VB-3691 Add config for onboarding BFI (Bedford)

server/constants/prisonConfiguration.ts
Changed child age from 9 to 10 for Durham
=> Updated DMI visitor guidance

server/constants/prisonConfiguration.ts
Now allow max of 4 visitors regardless of age. One must be an adult.
=> Changed SDI visitor guidance

helm_deploy/values-dev.yaml, helm_deploy/values-staging.yaml
=> Move to use CircleCI group in allowlists

server/constants/prisonConfiguration.ts
Adds changes to UI for prisons onboarding in Phase 3b:
BRI	Bure (HMP)
HPI	Highpoint (HMP)
LTI	Littlehey (HMP)
PVI	Pentonville (HMP & YOI)
Onboarding to service on 25/07.24
Applies to 
VB-4032
VB-4034
VB-4117
VB-4168
=> Phase 3b updates

integration_tests/integration/visitDetails.cy.ts, server/@types/orchestration-api.d.ts, server/constants/requestMethods.ts, server/routes/visit.test.ts, server/views/pages/visit/summary.njk
Use eventsAudit.userType to determine whether a website booking was PVB or VSiP Public
=> VB-3989, show public booking on visit history details page

server/constants/prisonConfiguration.ts
Changes for:
Norwich (HMP & YOI)
Warren Hill (HMP & YOI)
Hollesley Bay (HMP & YOI)
And small tweaks to existing prisons.
References: 
VB-4129
VB-4145
VB-4157
=> Added visitor rules for phase 3c prisons

integration_tests/mockApis/orchestration.ts, server/@types/orchestration-api.d.ts, server/data/orchestrationApiClient.test.ts, server/data/orchestrationApiClient.ts, server/services/visitSessionsService.test.ts, server/services/visitSessionsService.ts
Send username when making request to getVisitSessions
=> VB-4267, send username when making request to getVisitSesssions

Dockerfile, docker-compose.yml
Define git_branch in dockerfile
=> Fix dockerfile issue

assets/js/viewVisitsDatePicker.js, integration_tests/integration/datePicker.cy.ts, integration_tests/integration/visitsByDate.cy.ts, integration_tests/pages/visitsByDate.ts, server/views/pages/visits/summary.njk
Revert cypress tests to pre component version
Fix console logs from javascript file
=> VB-4399, datepicker component bug fixes

assets/sass/local.scss, server/@types/express/index.d.ts, server/data/orchestrationApiClient.test.ts, server/data/orchestrationApiClient.ts, server/routes/blockVisitDates/blockNewDateController.test.ts, server/routes/blockVisitDates/blockNewDateController.ts, server/routes/blockVisitDates/index.ts, server/services/blockedDatesService.test.ts, server/services/blockedDatesService.ts, server/views/pages/blockVisitDates/blockVisitDates.njk, server/views/pages/visits/summary.njk
'Wire-up' the block a date confirmation page so it calls the API to actually block the date.
N.B. Various `TODO`s present that will be sorted in upcoming PRs...
=> VB-3742 Block visit page - call API to add new blocked date

server/@types/bapv.d.ts, server/routes/blockVisitDates/blockNewDateController.test.ts, server/routes/blockVisitDates/blockNewDateController.ts, server/routes/blockVisitDates/blockVisitDatesController.test.ts, server/routes/blockVisitDates/blockVisitDatesController.ts, server/views/pages/blockVisitDates/blockVisitDates.njk
Add MoJ Banner component to show a success message when a visit date is blocked.
=> VB-3742 Add success message when date blocked

assets/sass/local.scss, integration_tests/integration/blockDates.cy.ts, integration_tests/pages/blockedVisits.ts, server/data/orchestrationApiClient.test.ts, server/data/orchestrationApiClient.ts, server/routes/blockVisitDates/blockNewDateController.test.ts, server/routes/blockVisitDates/blockVisitDatesController.test.ts, server/routes/blockVisitDates/index.ts, server/routes/blockVisitDates/unblockVisitDateController.test.ts, server/routes/blockVisitDates/unblockVisitDateController.ts, server/services/blockedDatesService.test.ts, server/services/blockedDatesService.ts, server/views/pages/blockVisitDates/blockVisitDates.njk
Make 'Unblock' links work to unblock visit dates.
=> VB-3745 Unblock visit dates

server/routes/blockVisitDates/blockVisitDatesController.test.ts, server/routes/blockVisitDates/blockVisitDatesController.ts, server/views/pages/blockVisitDates/blockVisitDates.njk
* Tweaks to settings for Date Picker component
* Refactor and improve date validation (e.g. reject 31st Feb rather than interpreting it as, e.g. 2nd March)
=> VB-3741 Block dates: refactor date validation

package-lock.json, package.json, server/middleware/setUpWebSession.ts
Remove uuid dependency and use Node's crypto.randomUUID() (as advised on https://www.npmjs.com/package/uuid)
=> Remove 'uuid' dependency and replace with crypto.randomUUID()

server/routes/bookAVisit.ts, server/routes/visit.ts, server/routes/visitJourney/checkYourBooking.test.ts, server/routes/visitJourney/checkYourBooking.ts, server/routes/visitJourney/dateAndTime.test.ts, server/routes/visitJourney/dateAndTime.ts, server/routes/visitJourney/overbooking.test.ts, server/routes/visitJourney/overbooking.ts, server/views/pages/bookAVisit/overbooking.njk
Add overbooking page into journey, after date and time page
=> VB-4385 add date and time overbooking page

integration_tests/e2e/establishmentNotSupported.cy.ts, server/views/pages/establishmentNotSupported.njk
...and add integration test accidentally missed in last PR.
=> VB-3753 Establishment not supported page text tweak

integration_tests/e2e/searchForAPrisoner.cy.ts, integration_tests/e2e/visitTimetable.cy.ts, integration_tests/pages/page.ts, server/config.ts, server/routes/blockVisitDates/blockVisitDatesController.test.ts, server/routes/index.test.ts, server/routes/review/visitsReviewListingController.test.ts, server/routes/review/visitsReviewListingController.ts, server/routes/search.test.ts, server/routes/timetable.test.ts, server/routes/visitJourney/checkYourBooking.test.ts, server/routes/visits.test.ts, server/utils/nunjucksSetup.ts, server/views/pages/blockVisitDates/blockVisitDates.njk, server/views/pages/bookAVisit/checkYourBooking.njk, server/views/pages/index.njk, server/views/pages/review/visitsReviewListing.njk, server/views/pages/search/prisoner.njk, server/views/pages/search/prisonerResults.njk, server/views/pages/search/visit.njk, server/views/pages/search/visitResults.njk, server/views/pages/timetable.njk, server/views/pages/visits/summary.njk, server/views/pages/visits/summary.test.ts, server/views/partials/breadcrumbs.njk, server/views/partials/breadcrumbs.test.ts
Add breadcrumbs instead of 'Back' links on main pages.
=> VB-3025 Add breadcrumbs

server/routes/prisoner.test.ts, server/routes/prisoner.ts, server/views/pages/prisoner/profile.njk
Add new content to prisoner profile page, include link to all alerts
=> VB-3017, add link to all prisoner alerts, with new content

server/views/layout.njk, server/views/pages/blockVisitDates/blockNewDate.njk, server/views/pages/blockVisitDates/blockVisitDates.njk, server/views/pages/bookAVisit/additionalSupport.njk, server/views/pages/bookAVisit/checkYourBooking.njk, server/views/pages/bookAVisit/confirmation.njk, server/views/pages/bookAVisit/dateAndTime.njk, server/views/pages/bookAVisit/mainContact.njk, server/views/pages/bookAVisit/overbooking.njk, server/views/pages/bookAVisit/requestMethod.njk, server/views/pages/bookAVisit/visitType.njk, server/views/pages/bookAVisit/visitors.njk, server/views/pages/error.njk, server/views/pages/establishmentNotSupported.njk, server/views/pages/index.njk, server/views/pages/prisoner/profile.njk, server/views/pages/review/visitsReviewListing.njk, server/views/pages/search/prisoner.njk, server/views/pages/search/prisonerResults.njk, server/views/pages/search/visit.njk, server/views/pages/search/visitResults.njk, server/views/pages/timetable.njk, server/views/pages/visit/cancel.njk, server/views/pages/visit/cancelConfirmation.njk, server/views/pages/visit/clearNotifications.njk, server/views/pages/visit/confirmUpdate.njk, server/views/pages/visit/summary.njk, server/views/pages/visits/summary.njk
Fix page title issues
Also address some bad tab spacing on particular pages
Also tackle VB-4728, opted for 'applicationName' as full title
=> VB-3644 page titles

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-staging.yaml
See https://github.com/ministryofjustice/cloud-platform/issues/6609
=> VB-4970: Use visits-nonprod alerts severity

server/views/pages/bookAVisit/dateAndTime.njk, server/views/pages/bookAVisit/dateAndTime.test.ts
Change text for each slot from `X table(s) available` to `X table(s) available of Y table(s)`.
=> VB-5151 Update table availability text on Select date/time page

integration_tests/mockApis/orchestration.ts, server/@types/orchestration-api.d.ts, server/data/orchestrationApiClient.test.ts, server/data/orchestrationApiClient.ts, server/routes/testutils/testData.ts, server/services/visitNotificationsService.test.ts
Pass the enabled notification types when requesting notification count so that an accurate number is returned.
=> VB-5150 Filter notification count

assets/sass/application.scss, assets/sass/local.scss, integration_tests/e2e/reviewAVisit.cy.ts, integration_tests/e2e/searchForABooking.cy.ts, integration_tests/e2e/updateAVisit.cy.ts, integration_tests/e2e/visitDetails.cy.ts, integration_tests/pages/visitDetails.ts, server/routes/visit/visitDetailsController.test.ts, server/routes/visit/visitDetailsController.ts, server/views/pages/visit/visitDetails.njk
* Redesign of booking details page
* clear up unused styles
Todo: sort out vertical spacing/padding.
=> VB-5110 Visit booking details page restructure and re-style

assets/sass/application.scss, assets/sass/local.scss, integration_tests/e2e/reviewAVisit.cy.ts, integration_tests/e2e/visitDetails.cy.ts, integration_tests/pages/visitDetails.ts, server/routes/visit/visitDetailsController.test.ts, server/views/pages/visit/visitDetails.njk
* Move visit notification messages to use warning component (based on error summary component but using orange)
* Move cancellation messages to above page heading
=> VB-5110 Visit notification warning summary component

assets/sass/application.scss, assets/sass/local.scss, integration_tests/e2e/reviewAVisit.cy.ts, integration_tests/e2e/visitDetails.cy.ts, integration_tests/pages/visitDetails.ts, server/routes/visit/visitDetailsController.test.ts, server/views/pages/visit/visitDetails.njk
Reverts ministryofjustice/book-a-prison-visit-staff-ui#953
=> Revert "VB-5110 Visit notification warning summary component"

assets/sass/application.scss, assets/sass/components/_bapv_headings.scss, assets/sass/local.scss, integration_tests/e2e/reviewAVisit.cy.ts, integration_tests/e2e/searchForABooking.cy.ts, integration_tests/e2e/updateAVisit.cy.ts, integration_tests/e2e/visitDetails.cy.ts, integration_tests/pages/visitDetails.ts, server/routes/visit/visitDetailsController.test.ts, server/routes/visit/visitDetailsController.ts, server/views/pages/visit/visitDetails.njk
* Redesign of visit booking details page (initial release; prisoner alerts/restrictions to come)
* Add custom heading styles
=> VB-4411 Visit booking details page redesign

.circleci/config.yml
Updated the version of Playwright image on Dockerfile
=> Updated the version of image for Playwright

server/data/orchestrationApiClient.test.ts, server/data/orchestrationApiClient.ts
Ensure that visit notifications (as well as visit events audit) are filtered by the enabled types.
=> VB-5038 Filter visit details notifications

integration_tests/e2e/updateAVisit.cy.ts, integration_tests/e2e/visitDetails.cy.ts, integration_tests/mockApis/orchestration.ts, server/@types/bapv.d.ts, server/@types/orchestration-api.d.ts, server/data/orchestrationApiClient.test.ts, server/data/orchestrationApiClient.ts, server/middleware/sessionCheckMiddleware.test.ts, server/middleware/sessionCheckMiddleware.ts, server/routes/prisoner.test.ts, server/routes/prisoner.ts, server/routes/testutils/testData.ts, server/routes/visit.test.ts, server/routes/visit.ts, server/routes/visit/visitDetailsController.ts, server/routes/visit/visitUtils.test.ts, server/routes/visit/visitUtils.ts, server/routes/visitJourney/additionalSupport.test.ts, server/routes/visitJourney/checkYourBooking.test.ts, server/routes/visitJourney/confirmation.test.ts, server/routes/visitJourney/dateAndTime.test.ts, server/routes/visitJourney/mainContact.test.ts, server/routes/visitJourney/overbooking.test.ts, server/routes/visitJourney/requestMethod.test.ts, server/routes/visitJourney/selectVisitors.test.ts, server/routes/visitJourney/visitType.test.ts, server/services/visitService.test.ts, server/services/visitService.ts
Tidy up after move to new endpoint for visit details page.
* remove get visit notifications endpoint
* remove unnecessary prisoner DoB from session data
* new `visitUtils.ts` for visit-related utils functions
=> VB-5112 Code tidy and refactor

assets/sass/local.scss, server/views/pages/bookAVisit/dateAndTime.njk, server/views/pages/bookAVisit/dateAndTime.test.ts
Show a session's visit room name below the visit time slot on the 'Select date and time' page.
=> VB-5299 Add room name to session schedule

server/config.ts, server/routes/testutils/appSetup.ts, server/routes/visit/visitDetailsController.test.ts, server/routes/visit/visitDetailsController.ts, server/routes/visit/visitUtils.test.ts, server/routes/visit/visitUtils.ts, server/views/pages/visit/visitDetails.njk, server/views/pages/visit/visitDetailsWrongEstablishment.njk
Visit details page
* split template for when visit details **cannot** be shown to simplify controller and template code
* extract logic for determining which visit action buttons to display to a utility function
=> VB-5216 Refactor visit details page action buttons

integration_tests/pages/blockVisitDates.ts, server/@types/bapv.d.ts, server/@types/express/index.d.ts, server/routes/blockVisitDates/blockNewDateController.test.ts, server/routes/blockVisitDates/blockNewDateController.ts, server/routes/blockVisitDates/blockVisitDatesController.test.ts, server/routes/blockVisitDates/blockVisitDatesController.ts, server/routes/blockVisitDates/unblockVisitDateController.test.ts, server/routes/blockVisitDates/unblockVisitDateController.ts, server/routes/prisoner.test.ts, server/routes/testutils/appSetup.ts, server/routes/testutils/testData.ts, server/routes/visit/cancelVisitController.test.ts, server/routes/visit/clearNotificationsController.test.ts, server/routes/visit/confirmUpdateController.test.ts, server/routes/visitJourney/additionalSupport.test.ts, server/routes/visitJourney/checkYourBooking.test.ts, server/routes/visitJourney/confirmation.test.ts, server/routes/visitJourney/dateAndTime.test.ts, server/routes/visitJourney/mainContact.test.ts, server/routes/visitJourney/overbooking.test.ts, server/routes/visitJourney/requestMethod.test.ts, server/routes/visitJourney/selectVisitors.test.ts, server/routes/visitJourney/visitJourneyUtils.ts, server/routes/visitJourney/visitType.test.ts, server/routes/visitorUtils.test.ts, server/routes/visitorUtils.ts, server/routes/visitsByDate.test.ts, server/utils/nunjucksSetup.ts, server/views/pages/blockVisitDates/blockVisitDates.njk
* Tidy up and make more consistent types for `req.flash()`
* Replace MoJ Banner component with Alert component when blocking visit dates
=> VB 5393 Switch from MoJ Banner to Alert component for blocking dates (and flash types refactor)

server/data/orchestrationApiClient.test.ts, server/data/orchestrationApiClient.ts, server/routes/visitJourney/checkYourBooking.ts, server/routes/visitJourney/dateAndTime.test.ts, server/routes/visitJourney/dateAndTime.ts, server/routes/visitJourney/overbooking.ts, server/routes/visitJourney/visitJourneyUtils.test.ts, server/routes/visitJourney/visitJourneyUtils.ts, server/services/visitSessionsService.test.ts, server/services/visitSessionsService.ts, server/views/pages/bookAVisit/dateAndTime.njk, server/views/pages/bookAVisit/dateAndTime.test.ts, server/views/pages/bookAVisit/overbooking.njk, server/views/pages/bookAVisit/visitors.njk, server/views/pages/visit/visitDetails.njk
* Move various messages on Select date and time page from using MoJ Banner component to Alert component
* Refactoring and tidying to improve code consistency
=> VB-5393 Select date and time page: use MoJ Alert component

integration_tests/e2e/updateAVisit.cy.ts, integration_tests/mockApis/prisonerContactRegistry.ts, server/@types/orchestration-api.d.ts, server/@types/prisoner-contact-registry-api.d.ts, server/data/prisonerContactRegistryApiClient.test.ts, server/data/prisonerContactRegistryApiClient.ts, server/routes/testutils/testData.ts, server/services/prisonerVisitorsService.test.ts, server/services/prisonerVisitorsService.ts
* update imported API definitions - to add `restrictionId` to contact (visitor) restrictions
* Move to the `/v2` contact registry API
=> VB-3758 API changes for restrictions (add restrictionId) and move to v2 contacts API

integration_tests/e2e/home.cy.ts, integration_tests/e2e/reviewVisitsList.cy.ts, integration_tests/pages/visitsReviewListing.ts, server/routes/index.test.ts, server/routes/review/visitsReviewListingController.test.ts, server/views/pages/index.njk, server/views/pages/review/visitsReviewListing.njk
* Update home page tile names
* Update heading on visits needing review listing
=> VB-5772, VB-5774 Content tweaks to homepage tiles and visit review page

assets/sass/local.scss, integration_tests/e2e/home.cy.ts, integration_tests/e2e/request/requestedVisitsList.cy.ts, integration_tests/mockApis/orchestration.ts, integration_tests/pages/request/visitRequestsListing.ts, server/@types/orchestration-api.d.ts, server/app.ts, server/data/orchestrationApiClient.test.ts, server/data/orchestrationApiClient.ts, server/data/orchestrationApiTypes.ts, server/routes/index.test.ts, server/routes/index.ts, server/routes/request/index.ts, server/routes/request/visitRequestsListingController.test.ts, server/routes/request/visitRequestsListingController.ts, server/routes/testutils/appSetup.ts, server/routes/testutils/testData.ts, server/routes/visit/visitDetailsController.test.ts, server/services/index.ts, server/services/testutils/mocks.ts, server/services/visitNotificationsService.test.ts, server/services/visitNotificationsService.ts, server/services/visitRequestsService.test.ts, server/services/visitRequestsService.ts, server/views/pages/request/visitRequestsListing.njk, server/views/pages/visit/visitDetails.njk
Add Requested visits listing page (wrapped in `FEATURE_VISIT_REQUEST` so only on dev & staging currently).
=> VB-5777 Requested visits listing page

integration_tests/e2e/request/processVisitRequest.cy.ts, integration_tests/pages/request/visitRequestsListing.ts, integration_tests/pages/visit/visitDetails.ts
Integration test for approving / rejecting a visit request.
=> VB-4953, VB-4954 Process visit request integration test

server/views/pages/request/visitRequestsListing.njk
Hide requested visits description text, if no requested visits present
=> VB-5842, hide requested visits description text
