- server/utils/nunjucksSetup.ts
Should fix templates not found error - which happens on Cloud Platform but not locally.
> Use full path for Nunjucks include path

- server/@types/bapv.d.ts
- server/services/visitSessionsService.test.ts
- server/services/visitSessionsService.ts
- server/utils/nunjucksSetup.test.ts
- server/utils/nunjucksSetup.ts
- server/views/pages/dateAndTime.njk
- server/views/pages/dateAndTime.test.ts
Keep hold of VisitSession timestamps as they will be needed to make the session booking.
Move time formatting to a Nunjucks filter so it can be re-used.
> Refactor Visit Slots and and add Nunjucks filter

- server/@types/express/index.d.ts
- server/routes/visitors.test.ts
- server/routes/visitors.ts
`offenderNo` wasn't coming through on POST requests (following failed validation) to get visitor list. Added to the session on the initial GET so it's available. Added test coverage for this.
> VB-326 Add offenderNo to session to fix 404s

- server/utils/nunjucksSetup.ts
- server/views/pages/dateAndTime.njk
These config options are giving much cleaner (and smaller!) HTML output on all pages. For date/time picker specifically there were some big chunks of whitespace caused by loops, have tweaked these in the template.
> Automatically remove whitespace in Nunjucks

- server/routes/visitors.test.ts
- server/routes/visitors.ts
- server/services/visitSessionsService.ts
* Fix create vs update visit logic
* Add logging for create/update visit operations
* Test coverage for calls to create/update visit session service (only in POST /visit/select-date-and-time)
> Fix update/create visit logic on select date and time page

- assets/sass/local.scss
- server/@types/bapv.d.ts
- server/routes/search.test.ts
- server/services/prisonerSearchService.test.ts
- server/services/prisonerSearchService.ts
- server/views/pages/prisoner/visits.njk
- server/views/pages/search/prisonerResults.njk
- server/views/pages/search/visitResults.njk
Simplify markup for tables by adding the extra spacing to the whole table (using class `bap-table`) rather than to every cell (using `bapv-table_cell`).
> Simplify tables: style table rather than each cell

- server/@types/visit-scheduler-api.d.ts
- server/data/visitSchedulerApiClient.test.ts
- server/data/visitSchedulerApiClient.ts
- server/services/visitSessionsService.test.ts
* update the types from the Visit Scheduler
* add the `visitStatus` filter (hard-coded to `BOOKED`) to `GET /visits` requests so that cancelled or reserved visits don't show in listings (e.g. on prisoner profile tabs or prisoner visits listing)
> VB-683 use visitStatus filter

- server/routes/prisoner.test.ts
- server/routes/prisoner.ts
- server/views/pages/prisoner/profile.njk
Current Prisoner Profile page behaviour is to:
* Render 'Book a prison visit' button as a link to continue the journey (on to Select Visitors)
* Populate `visitSessionData` with the requested prisoner on load
In preparation for VB-741 (adding VO override checkbox), this changes the page to:
* use the button to submit to a new POST route that redirects to the next step in the journey (and will be used to validate the checkbox)
* populates `visitSessionData` in the POST route so that the session is only 'started' when the Book button is pressed rather than just by viewing a profile
> VB-741: Refactor to use POST route to start booking journey

- server/utils/nunjucksSetup.test.ts
- server/utils/nunjucksSetup.ts
If a custom main contact was entered with a middle name (e.g. `Firstname Middlename Lastname`) this was rendered in the booking summary incorrectly as `Middlename, Firstname`. This fix displays it as `Lastname, Firstname`.
> Format contact with middle name correctly

- .circleci/config.yml
- docker-compose-test.yml
- helm_deploy/book-a-prison-visit-staff-ui/values.yaml
- integration_tests/mockApis/auth.ts
- integration_tests/mockApis/tokenVerification.ts
- integration_tests/plugins/index.ts
- package-lock.json
- package.json
- server/data/hmppsAuthClient.ts
- server/routes/index.ts
Bring in the most recent changes from https://github.com/ministryofjustice/hmpps-template-typescript
> VB-807: updates from template app

- server/middleware/sessionCheckMiddleware.test.ts
- server/middleware/sessionCheckMiddleware.ts
- server/routes/bookAVisit.test.ts
- server/routes/bookAVisit.ts
- server/routes/prisoner.test.ts
- server/routes/prisoner.ts
- server/services/visitSessionsService.test.ts
- server/services/visitSessionsService.ts
- server/views/pages/checkYourBooking.njk
- server/views/pages/confirmation.njk
- server/views/pages/dateAndTime.njk
- server/views/pages/dateAndTime.test.ts
Set `visitRestriction` (defaulting to `OPEN`) when `visitSessionData` is first created. Use this value throughout journey (instead of hardcoded 'Open') and use it to filter available date/time slots.
> VB-810: Use visitRestriction (open/closed) in session and to filter available slots

- server/@types/bapv.d.ts
- server/middleware/sessionCheckMiddleware.test.ts
- server/middleware/sessionCheckMiddleware.ts
- server/routes/bookAVisit.test.ts
- server/routes/bookAVisit.ts
- server/routes/prisoner.test.ts
- server/routes/prisoner.ts
- server/routes/visitorUtils.test.ts
- server/routes/visitorUtils.ts
- server/services/visitSessionsService.test.ts
- server/services/visitSessionsService.ts
- server/views/pages/confirmation.njk
Better handle session data and ensure it it cleared out to prevent existing bookings being amended rather than creating new ones.
* keeps `visitStatus` in session and checks this and visit reference added to session check middleware
* session date cleared at start/end of booking journey
* updated tests
> VB-826: Clear session after booking

- server/routes/bookAVisit.test.ts
- server/views/pages/visitors.njk
Add visitor fixes:
- When the prisoner has no active restrictions, do not display the restrictions tile
- Reduce the spacing between ‘prisoner name’ and their name to be consistent with next page
- Change placement of the rules text to be below approved visitor list title
> VB-633: Amend add visitors page

- server/@types/bapv.d.ts
- server/middleware/sessionCheckMiddleware.test.ts
- server/middleware/sessionCheckMiddleware.ts
- server/routes/bookAVisit.test.ts
- server/routes/bookAVisit.ts
- server/routes/prisoner.test.ts
- server/routes/prisoner.ts
- server/views/pages/dateAndTime.njk
- server/views/pages/dateAndTime.test.ts
If a visitor with a CLOSED restriction is selected:
* set the `visitRestriction` in the session to be `CLOSED`
* set the reason for closed visits in the session to be `visitor`
* show an information banner on the visit date/time picker page to explain why only closed visits are being shown.
(Previously the `visitRestriction` was set to a default of `OPEN` at the start of the session; this is now set at the next stage in the journey when visitors are selected so there is a small refactor of the session validation code.)
> VB-810: Only show closed slots for visitors with closed restriction

- server/views/pages/additionalSupport.njk
- server/views/pages/mainContact.njk
- server/views/pages/visit/cancel.njk
- server/views/partials/searchForPrisonerHeader.njk
Add's attribute autocomplete:"off" to the input fields
Stop the previously entered information from appearing and being suggested on these fields
Had to be tested manually as it's an attribute for an input field
> VB-870 found 4 input fields, autocomplete:off set

- server/@types/bapv.d.ts
- server/routes/bookAVisit.test.ts
- server/routes/bookAVisit.ts
- server/views/pages/dateAndTime.njk
- server/views/pages/visitType.njk
If the **prisoner** has a closed restriction then, after selecting visitors, show a page to choose visit type (open/closed) before proceeding to choose visit date/time. If a closed visit is chosen the reason for this ('prisoner') is stored to display in the subsequent banner.
If the **visitor** has a closed restriction then the visit type page is not used and the visit is automatically set to CLOSED.
> VB-811: Option to choose open/closed visit type for prisoners with 'closed' restriction

- server/routes/bookAVisit.ts
- server/views/pages/additionalSupport.njk
- server/views/pages/checkYourBooking.njk
- server/views/pages/confirmation.njk
- server/views/pages/dateAndTime.njk
- server/views/pages/mainContact.njk
- server/views/pages/prisoner/profile.njk
- server/views/pages/prisoner/visits.njk
- server/views/pages/visit/cancel.njk
- server/views/pages/visit/cancelConfirmation.njk
- server/views/pages/visit/summary.njk
- server/views/pages/visitType.njk
- server/views/pages/visitors.njk
- server/views/pages/visits/summary.njk
- server/views/partials/searchForPrisonerHeader.njk
- server/views/partials/searchForVisitHeader.njk
Adding `preventDoubleClick: true` to existing button components (in advance of putting more buttons in for the dead-end journey points). Saw some double clicking going on while observing user research; figured we may as well add this attribute.
> Prevent button double clicks

- server/routes/bookAVisit.test.ts
- server/views/pages/dateAndTime.njk
- server/views/pages/dateAndTime.test.ts
Previously, day/time filter wasn't shown if no slots available - creating a 'dead-end'. This change makes it always display.
> Date/time picker: always show day and time filter and tweak text

- server/routes/bookAVisit.test.ts
- server/views/pages/visitors.njk
This fixes a journey 'dead-end' on the Select Visitors page where a booking can't proceed if only banned or child visitors are listed. Instead of showing the Continue button, the back-to-start button is displayed.
> VB-597: Select visitors: handle only banned/child dead-end

- server/data/notificationsApiClient.test.ts
- server/services/notificationsService.test.ts
Add tests to cover GOV.UK notify API client and service.
> Tests for GOV.UK Notify integration

- server/@types/prison-offender-search.d.ts
- server/data/prisonerSearchClient.test.ts
- server/data/prisonerSearchClient.ts
- server/routes/search.test.ts
- server/routes/search.ts
- server/routes/visit.test.ts
- server/routes/visit.ts
- server/services/prisonerSearchService.test.ts
- server/services/prisonerSearchService.ts
- server/views/pages/visit/summary.njk
Viewing a visit or searching by visit reference could fail if the prisoner had transferred from Hewell or been released as the API endpoints used to look up prisoner details (e.g. name) were tied down to Hewell (as a requirement of the booking journey).
This change adds the `GET /prisoner/{id}` endpoint from the `global-search-resource` in Prisoner Offender Search API and uses this to retrieve prisoner details - but **only** when viewing a visit or searching by visit reference in order to keep booking journey behaviour unchanged.
(Until further work is done on requirements regarding prisoner transfer/release, the prisoner location on the visit summary page will show **Unknown** if the prisoner is no longer at Hewell.)
> VB-952: Handle missing prisoner data (e.g. prisoner transferred or released)

- server/routes/search.test.ts
- server/routes/search.ts
Empty search requests were no longer calling the search API but **were** still logging an audit event. This change only logs audit events for valid search terms (i.e. currently 2 characters or more).
> VB-1033: Don't sent audit event if empty search

- server/data/visitSchedulerApiClient.test.ts
- server/data/visitSchedulerApiClient.ts
- server/services/visitSessionsService.test.ts
- server/services/visitSessionsService.ts
Slots that shouldn't be available because of non-associations can be filtered out of the available list by passing `prisonerId` to the visit scheduler when requesting the list of available slots.
> VB-543: Incorporate non-associations into date picker page

- server/data/hmppsAuthClient.test.ts
Client tests
Did some normalisation of the jest functions being used
toBeCalledTimes ->  toHaveBeenCalledTimes
toBeCalledWith -> toHaveBeenCalledWith
> client-level, normalisation of tests

- server/services/prisonerProfileService.test.ts
- server/services/prisonerProfileService.ts
Prisoner profile page was calling contact registry both during getting past visits and upcoming visits. This charge:
* adds test data to cover contact registry and visit data
* refactors to only call the contact registry once for the profile page
> Remove duplicate call to contact registry on prisoner profile

- server/routes/bookAVisit.test.ts
- server/routes/visitJourney/checkYourBooking.ts
- server/routes/visitJourney/dateAndTime.ts
- server/services/auditService.test.ts
- server/services/auditService.ts
For the `RESERVED_VISIT` and `BOOKED_VISIT` audit messages, this change adds additional data to these:
* `visitorIds` (array of visitor IDs)
* `startTimestamp` of the visit
* `endTimestamp` of the visit
* `visitRestriction` (i.e. `OPEN` or `CLOSED`
> VB-1070: Add more details of visit to user audit

- server/data/visitSchedulerApiClient.ts
- server/routes/visit.ts
- server/services/visitSessionsService.ts
Remove startUpdateVisit and all of its references
The process around update visit has changed, we will no longer be changing the previous booking to reserved as this would mean the entire booking would be lost (to housekeeping) should this visit not be re-booked
> vb-1112, remove startUpdateVisit

- package.json
- server/@types/bapv.d.ts
- server/@types/express/index.d.ts
- server/routes/testutils/appSetup.ts
- server/routes/visit.test.ts
- server/routes/visit.ts
- server/routes/visitJourney/additionalSupport.ts
- server/routes/visitJourney/checkYourBooking.ts
- server/routes/visitJourney/confirmation.ts
- server/routes/visitJourney/dateAndTime.ts
- server/routes/visitJourney/selectVisitors.ts
- server/routes/visitJourney/visitType.test.ts
- server/routes/visitJourney/visitType.ts
- server/routes/visitorUtils.test.ts
- server/routes/visitorUtils.ts
- server/services/visitSessionsService.test.ts
- server/services/visitSessionsService.ts
- server/views/pages/bookAVisit/dateAndTime.njk
- server/views/pages/visit/additionalSupport.njk
- server/views/pages/visit/dateAndTime.njk
- server/views/pages/visit/visitType.njk
- server/views/pages/visit/visitors.njk
This change ensures that for an update visit journey a new visit is created each time, with the existing visit untouched. (Future work will 'swap' these over by booking the new one and cancelling the previous one.)
Most changes relate to refactoring to simplify by removing separate storing of old/new visit details in session.
To do in subsequent changes for this ticket:
* sort issues with table count showing negative values in some update scenarios
* tests for new visit creation
> VB-1112 Reserve new slot on update

- server/routes/visit.test.ts
- server/routes/visit.ts
Now that viewing booking summary populates session, ensure this is cleared once a visit is cancelled.
> VB-1072: Clear session after visit cancellation

- server/routes/bookAVisit.test.ts
- server/routes/bookAVisit.ts
- server/routes/visit.test.ts
- server/routes/visitJourney/checkYourBooking.ts
Once visit details are checked by user and confirmed:
* new visit is `BOOKED`
* previous visit is cancelled with the status `SUPERSEDED_CANCELLATION` and a text reference to the new visit's reference
* SMS for new, booked visit remains the same
* User audit logs both the booking of the new visit and the cancellation of the previous one
> VB-1113: Cancel previous visit when confirming updated visit

- server/routes/visit.test.ts
- server/routes/visitJourney/checkYourBooking.ts
Change the recorded outcome status to be simply the visit reference so it can be more easily processed, e.g. to be re-used to form a URL. Message to the user audit log is unchanged.
> Just use visit ref for SUPERSEDED_CANCELLATION reason text

- server/routes/visit.test.ts
- server/routes/visitJourney/checkYourBooking.ts
- server/views/pages/visit/summary.njk
Disable the buttons on the visit summary page when a visit has been superseded or cancelled already.
This work may be replaced when a design has been made but this ticket works for MVP.
On Superseded it displays the visit reference number for the new visit also links to the new visit and gives the new visit reference
> vb-1172-disable-update-and-cancel-on-unavailable

- server/routes/bookAVisit.test.ts
- server/routes/visitJourney/additionalSupport.ts
Attempting to fix the bug where additional support stays populated on both update journey and pre-booking changes.
When an additional support item has previously been selected, changing to none doesn't update the additional support in visitSessionData
> vb-1080, additional support wasn't being updated if changed to none

- .circleci/config.yml
- README.md
- package.json
- tsconfig.json
Run test coverage report by default (only seems to add a couple of seconds). Include the reports in build artefacts on CIrcleCI for reference. Document where to find these.
> Add test coverage, include in build artifacts and document

- server/views/pages/visits/summary.njk
Set `autocomplete` to `off` on the date picker on the 'View visits by date' page.
> VB-1196: Date picker: turn off autocomplete

- package.json
Recent update of `ts-jest` from 28 to 29 broke recent speed improvements for tests. Issue seems to be deprecation of way config is specified (https://github.com/kulshekhar/ts-jest/blob/main/CHANGELOG.md#2900-2022-09-08).
This moves config to the new syntax (https://kulshekhar.github.io/ts-jest/docs/getting-started/options).
> Update config for ts-jest v29

- docker-compose.yml
- server/routes/visitJourney/dateAndTime.ts
- server/views/pages/bookAVisit/dateAndTime.njk
- server/views/pages/bookAVisit/dateAndTime.test.ts
There is no way to stop the accordion component using sessions to remember what was open and closed, it overrides the values of `expanded` as that is already set correctly but ignored if an option was previously opened.
ID values can be 512Kb long, used uuid to ensure uniqueness.
Bad Paul, but the `docker-compose` having a common name of `redis` is causing no end of issues for me locally with other projects doing the same.
> VB-1180: Give accordions unique ID to stop session based selection

- server/@types/visit-scheduler-api.d.ts
- server/data/visitSchedulerApiClient.test.ts
- server/data/visitSchedulerApiClient.ts
- server/data/visitSchedulerApiTypes.ts
- server/services/visitSessionsService.test.ts
- server/services/visitSessionsService.ts
Add support for `PUT /visits/{reference}/change`, which returns a visit with status set to either `RESERVED` (where date/time or restriction different) or `CHANGING` (any other changes) and with a new `applicationReference`.
> VB-1208: Add support for new change booked visit endpoint

- assets/sass/local.scss
Fix issue where links on tabs component (on prisoner profile) were showing the wrong link `:visited` colour.
> VB-1181: Fix visited link colour on tabs

- server/middleware/sessionCheckMiddleware.test.ts
- server/middleware/sessionCheckMiddleware.ts
- server/routes/visit.ts
- server/routes/visitJourney/dateAndTime.test.ts
This chang:
* adds the existing `sessionCheckMiddleware` to the update visit routes (works without change now that the journey is effectively the same for book and update)
* adds an additional check to ensure that the visit reference in the URL (if present) matches that in the `visitSessionData`
> VB-1116: Update visit routes - add session and URL validation

- server/@types/bapv.d.ts
- server/data/visitSchedulerApiClient.test.ts
- server/data/visitSchedulerApiClient.ts
- server/middleware/sessionCheckMiddleware.test.ts
- server/middleware/sessionCheckMiddleware.ts
- server/routes/visit.test.ts
- server/routes/visit.ts
- server/routes/visitJourney/additionalSupport.test.ts
- server/routes/visitJourney/checkYourBooking.test.ts
- server/routes/visitJourney/checkYourBooking.ts
- server/routes/visitJourney/confirmation.test.ts
- server/routes/visitJourney/confirmation.ts
- server/routes/visitJourney/dateAndTime.test.ts
- server/routes/visitJourney/dateAndTime.ts
- server/routes/visitJourney/mainContact.test.ts
- server/services/notificationsService.test.ts
- server/services/notificationsService.ts
- server/services/visitSessionsService.test.ts
- server/views/pages/bookAVisit/checkYourBooking.njk
- server/views/pages/bookAVisit/confirmation.njk
This change renames `visit` in `visitSessionData` to be `visitSlot` to more accurately represent what it is.
* a 'visitSlot' is a combination of date, time and restriction (open/closed) - e.g. list of these are used when selecting date/time of visit
* a 'visit' represents the VisitDto from the visit scheduler; i.e. a visit with a reference, date/time, visitors, visit status, etc.
Hopefully this change will improve clarity in the code.
> Rename visit to visitSlot in visitSessionData

- package.json
Small tweak to Jest configuration so that code coverage runs when doing full test suite but not automatically when just running an individual test (e.g. with `npx jest <file.test.ts>`).
> Tweak jest code coverage config

- server/views/pages/bookAVisit/dateAndTime.njk
- server/views/pages/bookAVisit/dateAndTime.test.ts
Improve the labelling of date/time slots so that rather than displaying table count or "fully booked" when there is already a reserved slot (either when revising an initial booking or amending a booked visit) a more descriptive label is used.
> VB-1251: Improve slot labelling for book/update

- server/routes/search.test.ts
- server/routes/search.ts
Trim text input when searching for a prisoner.
(While looking in Application Insights, I noticed that users were commonly submitting search queries with trailing spaces so there was lots of unnecessary `%20` type encodings in the logs.)
> VB-1268: Trim text input on prisoner search

- assets/sass/local.scss
- server/routes/visit.test.ts
- server/views/pages/visit/summary.njk
Visit cancelled message on visit summary page now uses GDS warning component.
Tests run for visitor cancelled and administrative cancellation as they use different wordings.
Had to include some CSS as the GDS component doesn't natively support multiple lines of text
> VB 1255, cancelled visit message on summary page

- assets/sass/components/_header-bar.scss
Removed the display none from the service name CSS file for small screen sizes, meant the home page couldn't be navigated to if the user has a small screen size
> VB-1276, stop service title disappearing on smaller screensize

- assets/sass/local.scss
Stop the beta banner text getting too close to the right-hand edge of the screen on smaller sizes.
> VB-1223: Add padding to right of beta banner

- server/routes/visitJourney/dateAndTime.test.ts
- server/routes/visitJourney/dateAndTime.ts
- server/routes/visitorUtils.test.ts
- server/routes/visitorUtils.ts
- server/views/pages/bookAVisit/dateAndTime.njk
- server/views/pages/bookAVisit/dateAndTime.test.ts
The select date/time page shows restriction change messages to indicate that a visit needs to become open/closed and - depending on availability - whether or not a new time slot needs to be selected.
This change fixes an issue where a slot could be incorrectly selected even if the restriction change message indicated that is was not available.
> VB-1079: Fix restriction change messages and slot selection for amend journey

- server/middleware/setUpWebSecurity.ts
This change adds the the `HMPPS_AUTH_URL` to the CSP `form-action` directive so it is now, for example:
```
form-action 'self' https://sign-in-dev.hmpps.service.justice.gov.uk/auth;
```
If a user's session has expired, a subsequent `GET` page request would bounce via `/sign-in` and send the user to Auth to get a new session. If the session had expired and a `POST` request from a form was made, that request would end up 'stuck' as the re-authentication flow would be blocked by CSP. This change restores the previous behaviour by additionally allowing just the appropriate Auth domain.
This issue arose when Helmet was upgraded from [version 4 to 5](https://github.com/helmetjs/helmet/blob/main/CHANGELOG.md#500---2022-01-02) because of this change:
* Breaking: `helmet.contentSecurityPolicy`: …
> VB-1193: Fix '/sign-in' getting stuck following a form POST because of CSP

- server/middleware/setUpWebSecurity.ts
This change removes the `'upgrade-insecure-requests'` directive from the CSP when the application is in `development` mode.
This fixes the application for Safari when running on `localhost`. Other browsers don't try to upgrade insecure requests on `localhost` but Safari does - which means that assets like CSS, etc are blocked.
(This issue arose when Helmet was upgraded from [version 4 to 5](https://github.com/helmetjs/helmet/blob/main/CHANGELOG.md#500---2022-01-02) and a new default CSP was used that included `upgrade-insecure-requests`.)
> Change to CSP to fix for Safari on localhost

- server/@types/express/index.d.ts
- server/middleware/populateSelectedEstablishment.test.ts
- server/middleware/populateSelectedEstablishment.ts
- server/routes/standardRouter.ts
- server/routes/testutils/appSetup.ts
- server/routes/visitorUtils.test.ts
- server/routes/visitorUtils.ts
- server/views/partials/header.njk
This adds `selectedEstablishment` to the session. Currently it defaults to `HEI / Hewell (HMP)` - pending further work on the establishment switcher and a decision on what the default should be.
Middleware ensures that `res.locals` is populated with the currently selected establishment so it is available throughout the application and in templates.
Initially changed the hard-coded 'Hewell' in the page template to use the new value. (Next steps, replace all the other hard-coded instances...!)
> VB-1390: Add selected establishment to session

- assets/sass/local.scss
Add a background colour to the pop-up date picker on 'View visits by date' page so that at narrow window size the main content isn't visible underneath.
> VB-1495: Add default background colour to date picker

- server/app.ts
- server/constants/prisons.ts
- server/data/visitSchedulerApiClient.test.ts
- server/data/visitSchedulerApiClient.ts
- server/routes/changeEstablishment.ts
- server/routes/testutils/appSetup.ts
- server/services/supportedPrisonsService.test.ts
- server/services/supportedPrisonsService.ts
- server/views/pages/changeEstablishment.njk
Add initial `SupportedPrisonsService` and use this to populate the establishment switcher page.
* list of supported prison IDs is hard-coded in the visit scheduler API client until the relevant visit scheduler endpoint is completed
* A constants file is used for full prison details - longer term this can be replaced with a call to the Prison Register API
> VB-1409: Add supported prisons service

- server/routes/visitorUtils.test.ts
- server/routes/visitorUtils.ts
When `clearSession` is called, keep the `selectedEstablishment` set. This will prevent it inadvertently being defaulted to a different value to the one a user may have chosen.
> VB-1412: Keep selected establishment when clearing session

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-staging.yaml
- server/config.ts
- server/routes/changeEstablishment.ts
Adds feature flag for establishment switcher, specifically so far the `/change-establishment` route. Initially only enabled on the `dev` environment. Getting this in prior to merging #404, which will actually allow the establishment to be changed.
(Tests will be added to #404 once this is PR is in.)
> VB-1388: Add feature flag for establishment switcher

- server/app.ts
- server/routes/testutils/appSetup.ts
- server/routes/visit.test.ts
- server/routes/visit.ts
- server/services/supportedPrisonsService.test.ts
- server/services/supportedPrisonsService.ts
Prisoner's current location currently showing as either Hewell or Unknown on booking details page. 
This change displays the prisoners current location as long as it is in the list of supported prisons. Otherwise 'Unknown' is still shown (as a precaution against, for example, revealing a transfer or similar).
> VB-1402: Booking details page - show location if a supported prison

- integration_tests/mockApis/visitScheduler.ts
- server/data/visitSchedulerApiClient.test.ts
- server/data/visitSchedulerApiClient.ts
- server/routes/prisoner.ts
- server/services/prisonerProfileService.ts
- server/services/visitSessionsService.test.ts
- server/services/visitSessionsService.ts
This removes the `prisonId` parameter when calling `GET /visits` now that this is no longer required by the Visit Scheduler. 
This means that , for example, on a prisoner profile visit history tab visits from any prison will show instead of just those from the selected establishment.
> VB-1401: Remove prisonId from GET /visits call

- server/app.ts
- server/routes/changeEstablishment.test.ts
- server/routes/changeEstablishment.ts
- server/routes/testutils/appSetup.ts
- server/routes/visit.ts
- server/services/auditService.test.ts
- server/services/auditService.ts
Added audit event messages to successful establishment changes.
Logs the old and new establishment.
The second part of the ticket has already been covered, the only audit message that doesn't use currentEstablishment is visit search, which should show the visits prison, not the users.
> VB-1450 audit event - change establishment

- feature.env
- integration_tests/e2e/login.cy.ts
- integration_tests/e2e/searchForAPrisoner.cy.ts
- server/app.ts
- server/middleware/populateSelectedEstablishment.test.ts
- server/middleware/populateSelectedEstablishment.ts
- server/routes/changeEstablishment.test.ts
- server/routes/changeEstablishment.ts
- server/routes/prisoner.test.ts
- server/routes/search.test.ts
- server/routes/standardRouter.ts
- server/routes/testutils/appSetup.ts
- server/routes/visit.test.ts
- server/routes/visitJourney/checkYourBooking.test.ts
- server/routes/visitJourney/dateAndTime.test.ts
- server/routes/visitJourney/visitType.test.ts
- server/routes/visits.test.ts
- server/services/auditService.test.ts
- server/services/auditService.ts
This change:
* uses the user's caseload (set in DPS) to set the default selected establishment
* redirects the user to choose an establishment if the active caseload is not a supported VSiP prison
* maintains the already-selected prison in VSiP if the caseload in DPS is changed
If `FEATURE_ESTABLISHMENT_SWITCHER_ENABLED` is not enabled then the establishment defaults to `HEI / Hewell` regardless of the user's active caseload.
> VB-1412: Default selected establishment to user's active caseload

- server/routes/visit.test.ts
- server/routes/visit.ts
- server/views/pages/visit/summary.njk
Session data is now populated when entering the update journey, instead of when viewing a visit.
test data is used for both GET and POST methods, instead of having copies in each describe block
> VB-1449, load session data when updating visit, not viewing

- server/@types/bapv.d.ts
- server/data/visitSchedulerApiClient.test.ts
- server/data/visitSchedulerApiClient.ts
- server/middleware/sessionCheckMiddleware.test.ts
- server/middleware/sessionCheckMiddleware.ts
- server/routes/visit.test.ts
- server/routes/visit.ts
- server/routes/visitJourney/additionalSupport.test.ts
- server/routes/visitJourney/checkYourBooking.test.ts
- server/routes/visitJourney/confirmation.test.ts
- server/routes/visitJourney/dateAndTime.test.ts
- server/routes/visitJourney/dateAndTime.ts
- server/routes/visitJourney/mainContact.test.ts
- server/routes/visitorUtils.test.ts
- server/services/visitSessionsService.test.ts
- server/services/visitSessionsService.ts
- server/views/pages/bookAVisit/dateAndTime.test.ts
The existing `visitSessionData` didn't store the `prisonId` associated with the visit and instead relied on the `selectedEstablishment`. When looking up a visit by reference and with a different establishment selected to that of the visit, it was possible to start an update journey for the visit in the context of the 'wrong' prison (VB-1480).
This change adds `prisonId` to the `VisitSlot` type, which gets stored in `visitSessionData.visitSlot` (and `visitSessionData.originalVisitSlot` for update journey). This is then checked against the `selectedEstablishment` wherever `sessionCheckMiddleware` is used to make sure the two don't become mismatched. If they do, the request is redirected back to the home page.
Further work will avoid this kind of situation occurring and/or handling it better …
> VB-1481: Store prison ID in visit slot (in visitSessionData) and check against selected establishment

- server/routes/search.test.ts
- server/routes/search.ts
- server/services/visitSessionsService.test.ts
- server/services/visitSessionsService.ts
This change prevents the 'Search for a booking by reference' page from displaying a visit if is for a prison that is not the currently selected establishment.
> VB-1481: Restrict visit reference search to selected establishment

- server/routes/visit.test.ts
- server/routes/visit.ts
- server/views/pages/visit/summary.njk
On the booking summary page, do not show visit details if the visit is for a different prison to the user's currently selected establishment. Instead, show message saying what prison the visit is booked for and prompting user to switch establishment and search for it.
Applies the same check on POSTing to this page (i.e. starting a visit update journey).
(Also includes minor tweak to cancellation SMS to look up the prison name from the visit's `prisonId` rather than `selectedEstablishment` to avoid any potential mix-up.)
> VB-1481: Add selected establishment check to booking summary page

- server/routes/visits.test.ts
- server/routes/visits.ts
'View visits by date' page shows capacity counts hard-coded for Hewell. This change caters for Bristol having different values.
This is a temporary workaround until functionality added to calculate the capacity from the session template for the day.
> VB-1497: Visits by date - temp fix for capacity counts

- server/routes/visits.test.ts
- server/routes/visits.ts
Explicitly set capacity counts for Hewell, Bristol and 'default' on the 'View visits by date' page (change suggested as feedback #439)
(Still a temporary fix while working on how to derive these from session templates.)
> VB-1497: Explicitly set Hewell, Bristol and default capacity values

- .circleci/config.yml
Enable feature branches to be deployed to `dev` and `staging` environments. To support workflow of using both `main` and a `develop` branch.
> Allow feature branches to go to dev and staging

- server/app.ts
- server/data/prisonApiClient.test.ts
- server/data/prisonApiClient.ts
- server/index.ts
- server/routes/changeEstablishment.test.ts
- server/routes/changeEstablishment.ts
- server/routes/testutils/appSetup.ts
- server/services/userService.test.ts
- server/services/userService.ts
When changing establishment, also update the user's active case load so that this is reflected in, for example, DPS. Achieves this by calling `/api/users/me/activeCaseLoad` in the [Prison API](https://api-dev.prison.service.justice.gov.uk/swagger-ui/index.html#/users/updateMyActiveCaseLoad).
Caveats:
* if you are already logged into DPS and change establishment within VSiP, the selected establishment won't change in DPS until you next log in because the currently active case load is only looked up on login
* likewise, once logged into VSiP, any change of case load in DPS won't affect VSiP until next login
> VB-1421: Set case load for DPS when changing establishment

- server/data/__testutils/testObjects.ts
- server/data/visitSchedulerApiClient.test.ts
- server/routes/visitJourney/additionalSupport.test.ts
- server/routes/visitJourney/checkYourBooking.test.ts
- server/routes/visitJourney/confirmation.test.ts
- server/services/visitSessionsService.test.ts
createSupportTypes() can now be called in place of all availableSupportType declarations. 
No generator feature was used as these are always currently just carbon copy definitions of available support types
> VB-1540, remove supportTypes duplication, added to testObject

- server/routes/visit.test.ts
- server/routes/visit.ts
- server/routes/visitJourney/mainContact.test.ts
- server/routes/visitJourney/mainContact.ts
Trim whitespace so it isn't sent back to the visit scheduler when:
* entering a visit cancellation reason
* entering a custom main contact name
> VB-1547: Trim whitespace - visit cancellation reason & main contact name

- server/routes/visit.test.ts
- server/routes/visit.ts
Cancellation SMS had test data being sent out as the prison phone number.
Updated the Cancellation SMS function call to include the correct prison phone number, based on which prison the visit was booked for
> VB-1565, add Bristol+Hewell Prison phone numbers to cancellation

- server/data/notificationsApiClient.test.ts
- server/data/notificationsApiClient.ts
- server/routes/visit.test.ts
- server/routes/visit.ts
- server/services/notificationsService.test.ts
- server/services/notificationsService.ts
Add visit reference to Cancellation SMS to be used in Gov Notify.
Also changes the naming of a test data in notificationsApiClient.test as it was misleading
> VB-1600, Add reference to cancellation SMS

- .circleci/config.yml
Pin npm to 9.2.0 because of the issue https://github.com/npm/cli/issues/6051
See Slack thread https://mojdt.slack.com/archives/C69NWE339/p1673607422599409
> Pin CircleCI npm to 9.2.0

- .circleci/config.yml
Reverts ministryofjustice/book-a-prison-visit-staff-ui#466
Issue with `npm` that required us to pin the version now looks to be fixed (https://github.com/npm/cli/releases/tag/v9.3.1)
> Revert "Pin CircleCI npm to 9.2.0"

- server/constants/prisonConfiguration.test.ts
- server/constants/prisonConfiguration.ts
- server/routes/visit.ts
- server/routes/visitJourney/selectVisitors.test.ts
- server/routes/visitJourney/selectVisitors.ts
- server/routes/visits.test.ts
- server/routes/visits.ts
- server/views/pages/bookAVisit/visitors.njk
- server/views/pages/visits/summary.njk
* Consolidate prison-specific information (phone number, advisory text for visitors numbers, slot capacities) into a simple lookup function.
* It defaults to empty values if a prison hasn't been configured, meaning that new supported prisons can be tested before specific configuration information is available
* Update code and tests to use this information
This change means that adding appropriate configuration information for new prisons now only requires adding entries to `server/constants/prisonConfiguration.ts` rather than changing custom code in multiple places. (Longer-term this may be reworked as the orchestration service may end up proving some of this information.)
> VB-1594: Consolidate prison specific config

- server/routes/visitJourney/dateAndTime.ts
- server/routes/visitorUtils.test.ts
- server/routes/visitorUtils.ts
- server/services/visitSessionsService.test.ts
- server/services/visitSessionsService.ts
Error caused by overlapping sessions in Cardiff's visit schedule
Caused by the fact there is a session with no capacity for the currently selected visit restriction (the sessions have either open or closed, not both)
Current iteration only pushes the slot on a boolean check,  testing whether the current restriction has any capacity on the slot (initial capacity not available tables)
> VB-1731, overlapping sessions bug fix

- helm_deploy/values-dev.yaml
- server/routes/visitJourney/dateAndTime.test.ts
- server/routes/visitJourney/dateAndTime.ts
- server/services/visitSessionsService.test.ts
- server/services/visitSessionsService.ts
- server/views/pages/bookAVisit/dateAndTime.njk
* catches errors from the whereabouts API and handles these by showing message informing user that the data is unavailable, but booking can proceed
* previous behaviour would cause errors from whereabouts to 'bubble up' and prevent user from continuing
> VB-1751: Allow bookings to proceed if Whereabouts API is unavailable

- helm_deploy/values-dev.yaml
Use visits orchestration service instead of visit scheduler for dev environment only. To enable testing that new service is successfully providing all endpoints.
(Pre-cursor to moving all environments over and re-factoring front-end code to be more appropriately named.)
> VB-1830: Use visits orchestration service in dev environment

- integration_tests/integration/login.cy.ts
- integration_tests/mockApis/auth.ts
- integration_tests/pages/authorisationError.ts
Add integration test to cover user without `ROLE_MANAGE_PRISON_VISITS` role being redirected to auth error page.
(Will add something to `server/routes/testutils/appSetup.ts` to cover roles in unit tests once that's refactored as part of VB-1430.)
> VB-1857: Add integration test for user role check

- assets/sass/local.scss
- server/routes/timetable.test.ts
- server/routes/timetable.ts
- server/routes/visits.test.ts
- server/routes/visits.ts
- server/routes/visitsUtils.test.ts
- server/routes/visitsUtils.ts
- server/utils/utils.test.ts
- server/utils/utils.ts
- server/views/pages/timetable.njk
Add navigation for selecting the day to view on the 'Visits timetable' page (see screenshot).
* defaults to selecting the Monday of the current week
* navigation to previous / next week (using MoJ pagination styles)
* invalid date selection in URL renders current week
* tests for link generation and page rendering
(Visits timetable page protected by `FEATURE_VIEW_TIMETABLE_ENABLED` flag. Currently only enabled on dev.)
> VB-1841: Add Visits timetable date navigation

- server/@types/bapv.d.ts
- server/routes/visit.ts
Minor tweak to improve types. `VisitSlot.visitRestriction` and `visitSessionData.visitRestriction` are used in the context of the booking journey and should only ever be `'OPEN' | 'CLOSED'`. 
A `Visit` can have `visitRestriction` of `UNKNOWN` but this should only be relevant of viewing old migrated visits that can't be updated.
> VB-1835: Don't allow VisitRestriction to be UNKNOWN on VisitSlot

- integration_tests/integration/visitTimetable.cy.ts
- server/routes/timetable.test.ts
- server/views/pages/timetable.njk
Styling location groups as a single comma separated string looks confusing because the names themselves have commas inside..
This change renders the group names as a list.
> VB-1840 Style location group names as a list

- server/services/notificationsService.test.ts
- server/services/notificationsService.ts
- server/services/prisonerProfileService.test.ts
- server/services/prisonerProfileService.ts
- server/services/prisonerSearchService.test.ts
- server/services/prisonerSearchService.ts
- server/services/prisonerVisitorsService.test.ts
- server/services/prisonerVisitorsService.ts
- server/services/supportedPrisonsService.test.ts
- server/services/supportedPrisonsService.ts
- server/services/userService.test.ts
- server/services/userService.ts
- server/services/visitSessionsService.test.ts
- server/services/visitSessionsService.ts
Follow on from #517, and part of implementing changes in https://github.com/ministryofjustice/hmpps-template-typescript/pull/106. 
Following consolidation of the data access layer in #517, this change is to refactor services and their tests to use named imports from `../data` and standardise mocking dependencies in tests.
> VB-1430 Refactor services and tests following data access layer changes

- server/app.ts
- server/index.ts
- server/routes/bookAVisit.ts
- server/routes/changeEstablishment.test.ts
- server/routes/changeEstablishment.ts
- server/routes/prisoner.test.ts
- server/routes/prisoner.ts
- server/routes/search.test.ts
- server/routes/search.ts
- server/routes/standardRouter.ts
- server/routes/testutils/appSetup.ts
- server/routes/timetable.test.ts
- server/routes/timetable.ts
- server/routes/visit.test.ts
- server/routes/visit.ts
- server/routes/visitJourney/checkYourBooking.test.ts
- server/routes/visitJourney/dateAndTime.test.ts
- server/routes/visitJourney/selectVisitors.test.ts
- server/routes/visitJourney/visitType.test.ts
- server/routes/visits.test.ts
- server/routes/visits.ts
- server/services/index.ts
- server/services/testutils/mocks.ts
Follow on from #518, and part of implementing changes in https://github.com/ministryofjustice/hmpps-template-typescript/pull/106.
This change rewires the app to use a `Services` container so dependencies can be passed around more easily and without the need for so much duplication and disruption when services are changed. A lot of changes here, but basically all repetition of the same change to main and corresponding test file.
> VB-1430 Use services container

- server/data/testutils/mocks.ts
- server/middleware/populateSelectedEstablishment.test.ts
- server/services/notificationsService.test.ts
- server/services/prisonerProfileService.test.ts
- server/services/prisonerSearchService.test.ts
- server/services/prisonerVisitorsService.test.ts
- server/services/supportedPrisonsService.test.ts
- server/services/userService.test.ts
- server/services/visitSessionsService.test.ts
Add helper functions to create mock API clients to simplify and avoid repetition in test set up.
> VB-1430 Simplify mocks set up in tests

- server/data/prisonerContactRegistryApiClient.ts
- server/routes/visitJourney/additionalSupport.ts
- server/routes/visitJourney/checkYourBooking.ts
We're getting occasional errors relating to additional support options. They appear on the 'check your booking' page, e.g.
```
TypeError: Cannot read properties of undefined (reading 'map')
at getSupportTypeDescriptions (/app/dist/server/routes/visitorUtils.js:30:27)
at CheckYourBooking.get (/app/dist/server/routes/visitJourney/checkYourBooking.js:21:81)
```
This PR adds some logging to try and debug how this is happening. Expected kind of log messages:
```
[Node] 08:41:16.380Z  INFO Book A Prison Visit Staff Ui: choose support visitorSupport debug: {"additionalSupportRequired":"yes","additionalSupport":["WHEELCHAIR"],"visitorSupport":[{"type":"WHEELCHAIR"}],"availableSupportTypes":5}
[Node] 08:41:46.411Z  INFO Book A Prison Visit Staff Ui: check booking visitorSupport debug: …
```
> VB-2004 Add logging to debug 'undefined' error for additional support

- server/config.ts
Set web session timeout to 120 mins to reflect template default and be more in line with other apps. Hopefully will reduce number of errors relating to users having expired session.
> VB-2004 Increase web session timeout to 120 mins

- server/routes/changeEstablishment.ts
- server/routes/prisoner.ts
- server/routes/visit.ts
- server/routes/visitJourney/additionalSupport.ts
- server/routes/visitJourney/dateAndTime.ts
- server/routes/visitJourney/mainContact.ts
- server/routes/visitJourney/selectVisitors.ts
- server/routes/visitJourney/visitType.ts
Address issues from CodeQL scan warnings of `Untrusted URL redirection` because of using `req.originalUrl` as the basis of redirects. E.g. https://github.com/ministryofjustice/book-a-prison-visit-staff-ui/security/code-scanning/6
> VB-2073 Fix some warnings from CodeQL scan

- server/routes/visit.test.ts
- server/views/pages/visit/summary.njk
If details of user who booked / updated / created is not available (e.g. old data) then don't display anything. The API returns `NOT_KNOWN` in these cases, so this change catches this value.
> VB-1927 Don't show user name if NOT_KNOWN

- server/@types/orchestration-api.d.ts
- server/@types/prison-api.d.ts
- server/@types/prisoner-offender-search-api.d.ts
- server/@types/whereabouts-api.d.ts
- server/data/orchestrationApiTypes.ts
Orchestration service now correctly returns several properties as `enum` rather than `string` so types updated to reflect this and workaround removed.
> VB-2081 Update types and remove workaround for enums as strings

- cypress.config.ts
- integration_tests/integration/bookAVisit.cy.ts
- integration_tests/integration/prisonerProfile.cy.ts
- integration_tests/mockApis/orchestration.ts
- integration_tests/pages/prisonerProfile.ts
- server/@types/bapv.d.ts
- server/@types/orchestration-api.d.ts
- server/@types/prison-api.d.ts
- server/@types/prisoner-offender-search-api.d.ts
- server/@types/whereabouts-api.d.ts
- server/data/orchestrationApiClient.ts
- server/data/orchestrationApiTypes.ts
- server/routes/prisoner.test.ts
- server/routes/prisoner.ts
- server/services/index.ts
- server/services/prisonerProfileService.test.ts
- server/services/prisonerProfileService.ts
- server/services/testutils/mocks.ts
- server/utils/utils.ts
- server/views/pages/prisoner/profile.njk
New endpoint being called
Forcing `PrisonerProfile` `visits` array to use @tpmcgowan previous temporary fix:  line 11: `server/data/orchestrationApiTypes.ts` 
This includes part of the work for VB-1468 (Single Visits tab)
Notes:
`VisitBalancesDto` doesn't include the next adjust date, for VO or PVO's.
Possibly new `VisitDto` for returning all visitor names
2 tests skipped for VO count being returned on a REMAND prisoner
1 test skipped for 404 being returned on no prisoner returned
> VB-1866, PrisonerProfile DTO 

- integration_tests/integration/visitTimetable.cy.ts
- server/@types/orchestration-api.d.ts
- server/@types/prison-api.d.ts
- server/@types/prisoner-offender-search-api.d.ts
- server/@types/whereabouts-api.d.ts
- server/routes/testutils/testData.ts
- server/routes/timetable.test.ts
- server/views/pages/timetable.njk
Update the visits timetable page so that the 'Attendees' column includes prisoner category groups as well as enhanced IEP status and location groups.
> VB-1999 Add descriptor to visits timetable page for prisoner category

- server/utils/azureAppInsights.test.ts
- server/utils/azureAppInsights.ts
Adds `username` and `activeCaseLoadId` as custom dimensions to requests in App Insights.
Based on https://github.com/ministryofjustice/use-of-force/pull/599
> VB-2167 Add user info to App Insights

- assets/sass/components/_prisoner-profile.scss
- integration_tests/integration/prisonerProfile.cy.ts
- integration_tests/pages/prisonerProfile.ts
- server/@types/bapv.d.ts
- server/data/orchestrationApiClient.test.ts
- server/routes/prisoner.test.ts
- server/routes/prisoner.ts
- server/routes/testutils/testData.ts
- server/services/index.ts
- server/services/prisonerProfileService.test.ts
- server/services/prisonerProfileService.ts
- server/services/testutils/mocks.ts
- server/utils/utils.ts
- server/views/pages/prisoner/profile.njk
Change the Visits tab on the Prisoner profile page to show upcoming and past visits grouped by month with totals. E.g.
Only past visits from recent months (past 3 - controlled by orchestration service) are shown. Full history available by link button at the bottom to listing page within DPS.
> VB-2061 Prisoner profile page visits tab – group visits by month

- server/routes/prisoner.test.ts
- server/views/pages/prisoner/profile.njk
* Update the message in the Visits tab on prisoner profile page that is displayed when the prisoner has no upcoming or recent past visits
* Add a test to cover this scenario
> VB-2061 Prisoner profile page Visits tab - update no visits message

- README.md
- assets/js/voOverride.js
- package-lock.json
- package.json
- server/routes/visitJourney/dateAndTime.ts
- server/views/pages/bookAVisit/dateAndTime.njk
- server/views/pages/bookAVisit/dateAndTime.test.ts
New version of [GOV.UK](http://gov.uk/) Frontend available: [Release GOV.UK Frontend v4.6.0 · alphagov/govuk-frontend](https://github.com/alphagov/govuk-frontend/releases/tag/v4.6.0)
- Updated library version.
- Book a visit: accordion internally improved, new property `rememberExpanded`
> VB-2198 update govuk frontend version

- integration_tests/integration/prisonerProfile.cy.ts
- server/@types/bapv.d.ts
- server/routes/prisoner.test.ts
- server/routes/testutils/testData.ts
- server/services/prisonerProfileService.test.ts
- server/services/prisonerProfileService.ts
- server/views/pages/prisoner/profile.njk
Build the HTML for alerts table rows in the template instead of `PrisonerProfileService`. Consistent with how Visits and Visiting orders tabs are generated – and simplifies testing.
> VB-2161 Prisoner profile page - refactor alerts table

- cypress.config.ts
- integration_tests/mockApis/orchestration.ts
- integration_tests/mockApis/visitScheduler.ts
- server/data/orchestrationApiClient.test.ts
- server/data/orchestrationApiClient.ts
- server/data/visitSchedulerApiClient.test.ts
- server/data/visitSchedulerApiClient.ts
- server/services/index.ts
- server/services/supportedPrisonsService.test.ts
- server/services/supportedPrisonsService.ts
Part of refactoring from using visit scheduler to orchestration service.
* Move `getSupportedPrisonIds()` to `orchestrationApiClient`
> VB-1834: Move getSupportedPrisonIds() to orchestration API client

- server/data/restClient.test.ts
- server/data/restClient.ts
- server/sanitisedError.test.ts
- server/sanitisedError.ts
Bring in changes from TypeScript template app to no longer default to retrying requests for `POST` or `PUT`.
> VB-2345 Don't retry POST or PUT requests

- server/routes/visitJourney/selectVisitors.test.ts
- server/routes/visitJourney/selectVisitors.ts
- server/views/pages/bookAVisit/visitors.njk
Added no permitted/approved visitors warning banner to select visitors page.
Test added to test for both possible messages
Also changed previous implementation on disabling the checkboxes on this page when the journey isn't able to go ahead
G3094UO - Hewell - All banned visitors
G8316GA - Hewell - Only child visitors
G9472UP - Hewell - No visitors
> VB-2125, added no approved/permitted warning message

- server/routes/visitJourney/selectVisitors.test.ts
- server/views/pages/bookAVisit/visitors.njk
Temporary fix to issue whereby child visitor checkboxes are being wrongly disabled. This fix stops checkboxes being disabled unless the visitor is banned.
> VB-2376 Temporary fix - don't disable visitor checkboxes (unless banned)

- server/@types/bapv.d.ts
- server/data/orchestrationApiClient.test.ts
- server/middleware/sessionCheckMiddleware.test.ts
- server/routes/visitJourney/additionalSupport.test.ts
- server/routes/visitJourney/checkYourBooking.test.ts
- server/routes/visitJourney/confirmation.test.ts
- server/routes/visitJourney/mainContact.test.ts
- server/routes/visitJourney/selectVisitors.test.ts
- server/routes/visits.test.ts
- server/services/prisonerVisitorsService.test.ts
- server/services/visitService.test.ts
- server/utils/visitorUtils.ts
Change `adult` on `visitorListItem` to be required, in the case that no DOB is returned, adult should be set to true (Based on business logic)
> Make adult required field, updated tests which had undefined

- cypress.config.ts
- integration_tests/integration/bookAVisit.cy.ts
- integration_tests/integration/checkYourBooking.cy.ts
- integration_tests/integration/updateAVisit.cy.ts
- integration_tests/mockApis/orchestration.ts
- server/data/orchestrationApiClient.test.ts
- server/services/visitService.test.ts
Previously calling the `/book` endpoint didn't require a request body so tests weren't accounting for this. This change adds checks for the `aplicationMethod` on the request body.
> VB-2540 Update unit and integration tests to include request body for PUT /book

- server/routes/prisoner.test.ts
- server/views/pages/prisoner/profile.njk
Prisoner profile page visits tab month headers show past / upcoming totals - e.g. `August 2023 (1 upcoming)`. If a month **only** had cancelled visit, it would incorrectly render `August 2023 ()`
This fixes it to just show `August 2023` in this case.
> VB-2575 Fix profile tab month headers

- integration_tests/integration/bookAVisit.cy.ts
- integration_tests/integration/prisonerProfile.cy.ts
- server/@types/bapv.d.ts
- server/@types/orchestration-api.d.ts
- server/data/orchestrationApiTypes.ts
- server/routes/prisoner.test.ts
- server/routes/prisoner.ts
- server/routes/testutils/testData.ts
- server/services/index.ts
- server/services/prisonerProfileService.test.ts
- server/services/prisonerProfileService.ts
- server/services/testutils/mocks.ts
- server/views/pages/prisoner/profile.njk
Use updated `PrisonerProfileDto` that contains visits as `VisitSummaryDto`. These include prison name and visitor names. This avoids having to make an additional calls to look these up separately in the contact registry / prison register.
> VB-2416 Use updated prisoner profile (containing visitor names)

- integration_tests/integration/bookAVisit.cy.ts
- integration_tests/integration/cancelVisit.cy.ts
- integration_tests/integration/changeEstablishment.cy.ts
- integration_tests/integration/checkYourBooking.cy.ts
- integration_tests/integration/home.cy.ts
- integration_tests/integration/login.cy.ts
- integration_tests/integration/prisonerProfile.cy.ts
- integration_tests/integration/searchForABooking.cy.ts
- integration_tests/integration/searchForAPrisoner.cy.ts
- integration_tests/integration/updateAVisit.cy.ts
- integration_tests/integration/visitDetails.cy.ts
- integration_tests/integration/visitTimetable.cy.ts
- integration_tests/integration/visitsByDate.cy.ts
- integration_tests/mockApis/prisonRegister.ts
- server/@types/bapv.d.ts
- server/@types/express/index.d.ts
- server/@types/prison-register-api.d.ts
- server/data/prisonRegisterApiClient.test.ts
- server/data/prisonRegisterApiClient.ts
- server/data/prisonRegisterApiTypes.ts
- server/middleware/populateSelectedEstablishment.test.ts
- server/routes/changeEstablishment.test.ts
- server/routes/changeEstablishment.ts
- server/routes/testutils/testData.ts
- server/routes/visitorUtils.test.ts
- server/services/supportedPrisonsService.test.ts
- server/services/supportedPrisonsService.ts
Use new endpoint that just returns prison code/name (`/prisons/names`) in place of the existing `/prisons` that returns a lot of unnecessary data. The list of names is still cached within the `SupportedPrisonsService`.
Most of the changes are actually just updating variable names to be more appropriate.
> VB-3181 Use new 'prison names' Prison Register endpoint

- assets/js/datepicker.js
- integration_tests/integration/datePicker.cy.ts
- integration_tests/pages/visitsByDate.ts
Fix two bugs found in the date picker component:
* bug where navigating between months / years would go to the wrong month. E.g. with 31st October selected, pressing the 'next month' button would take you to December instead of November. The cause was not handling JavaScript dates wrapping if trying to set an invalid date (e.g. in the previous example, 31st November would be invalid so it wrapped to December)
* bug where the month would be truncated to not show the '1st' if this day fell on a Sunday (e.g. Sunday 1st October 2023)
Some Cypress test coverage has been added for these scenarios (ideally to be removed if/when this component is moved to a pattern library)
> VB-3177, VB-3182 Fix Date Picker month/year navigation and missing dates

- helm_deploy/book-a-prison-visit-staff-ui/Chart.yaml
- helm_deploy/book-a-prison-visit-staff-ui/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-staging.yaml
This PR migrates the project to use groups of IPs in their allowlist.
By referring to groups to IP addresses, we can centralize the definition of groups of ip addresses.
If these lists require changing in the future, we can change the definition once and future deploys across all services will automatically include these new IPs.
3 allowlist(s) have been detected that can be migrated.
The effect of applying this PR is as follows:
- The following groups will be applied: `internal,prisons`
- The size of the allowlist defined in this file will change: `24 => 0 (24 removed)`
The new Group membership will result in the following IPs being added to your allowlist by applying this PR:
- mojo-azure-landing-zone-public-egress-1
- mojo-azure-landing-zone-public-egress-2
- …
> Migrating project to use groups in allowlist

- server/config.ts
- server/data/notificationsApiClient.test.ts
- server/data/notificationsApiClient.ts
When sending a cancellation SMS, if a prison doesn't have a contact number use a different Notify template that doesn't include this data.
> VB-3283 Cancellation SMS - handle prisons with no phone number

- .circleci/config.yml
Reduce complexity in the CircleCI build by using a `maven` image that already has Git installed so we don't need to install it as an extra job.
(See 'Image variants' on https://hub.docker.com/_/maven for details.)
> Acceptance tests - use Docker image with Git pre-installed

- integration_tests/integration/changeEstablishment.cy.ts
- server/routes/changeEstablishment.test.ts
- server/routes/changeEstablishment.ts
Fix issue where user arriving in the service (from DPS) with an unsupported caseload would not be able to successfully change to a supported caseload.
> VB-3200 Fix 'change establishment' error when user has unsupported case load

- helm_deploy/values-staging.yaml
With v2.9.2 of the Application Insights client (https://github.com/microsoft/ApplicationInsights-node.js/releases/tag/2.9.2) the app failed in staging because of an invalid key.
App insights isn't set up on staging so this PR unsets the relevant config values to stop it being used.
> Disable App Insights in staging

- helm_deploy/values-preprod.yaml
- server/constants/notificationEvents.ts
* Also, only show details about the two event types being initially released
> VB-3015 Enable pro-active bookings review in pre-prod

- integration_tests/pages/additionalSupport.ts
- integration_tests/pages/cancelVisit.ts
- integration_tests/pages/mainContact.ts
- integration_tests/pages/page.ts
- integration_tests/pages/selectVisitDateAndTime.ts
- integration_tests/pages/visitsByDate.ts
`Cypress-axe` was previously configured to only log accessibility violations. It will now fail a test if there is a violation.
Add a means to define `axeRulesToIgnore` (an array of rule names) in the `Page` test classes so that known accessibility issues (e.g. in GOV.UK components) can be ignored for that particular page.
> VB-2099 Cypress-axe - fail on violations and add ignore list for known accessibility violations

- server/services/visitService.ts
If no additional support set, orchestration doesn't return the `visitorSupport` object, this checks if the object exists before defining in local session data
> Change service level implementation when returning additional support

- server/views/pages/visit/summary.njk
Missing parentheses meant that the `<span>` with the `data-test` attribute wasn't getting generated properly.
> Fix test attribute

- server/views/pages/timetable.njk
Remove second paragraph on timetable page, as no longer required
> VB-3586, remove second paragraph

- integration_tests/integration/datePicker.cy.ts
- integration_tests/integration/visitsByDate.cy.ts
- integration_tests/mockApis/orchestration.ts
- server/@types/bapv.d.ts
- server/data/orchestrationApiClient.test.ts
- server/data/orchestrationApiClient.ts
- server/routes/visits.test.ts
- server/routes/visits.ts
- server/routes/visitsUtils.test.ts
- server/routes/visitsUtils.ts
- server/services/visitService.test.ts
- server/services/visitService.ts
- server/utils/utils.test.ts
- server/utils/utils.testData.ts
- server/utils/utils.ts
- server/views/pages/visits/summary.njk
- server/views/pages/visits/summary.test.ts
Building on #717, this adds support for 'unknown' visits to the re-implementation of the View visits by date page. 'unknown' visits means those that have been migrated and therefore don't have a session template reference and may also have a restriction type of `UNKNOWN` instead of `OPEN / CLOSED`.
Because the session schedule and visits-by-template-reference endpoints cannot retrieve these visits, they need to be looked up separately and parsed to construct a navigation based on the time slots that are discovered.
On the page, these are shown under the heading 'All visits', e.g.:
> VB-3296 Visits by date page: handle 'unknown' visits

- server/@types/bapv.d.ts
- server/@types/orchestration-api.d.ts
- server/middleware/populateSelectedEstablishment.test.ts
- server/middleware/populateSelectedEstablishment.ts
- server/middleware/sessionCheckMiddleware.test.ts
- server/routes/changeEstablishment.test.ts
- server/routes/changeEstablishment.ts
- server/routes/testutils/appSetup.ts
- server/routes/testutils/testData.ts
- server/routes/visit.test.ts
- server/routes/visitJourney/selectVisitors.test.ts
- server/routes/visitJourney/selectVisitors.ts
- server/routes/visitorUtils.test.ts
- server/services/supportedPrisonsService.test.ts
- server/services/supportedPrisonsService.ts
Replace the hard-coded maximum of 10 visitors that can be selected for a visit with the configurable value that is now available per prison.
> VB-3729 Use the prison's configured maximum total visitors when validating on 'Select visitors' page

- integration_tests/integration/reviewAVisit.cy.ts
- server/routes/visit.test.ts
- server/routes/visit.ts
- server/views/pages/visit/summary.njk
If the only visit notification is for a blocked date then do not show the 'Do not change' button on the booking summary page.
> VB-3760 Hide 'Do not change' button if only notification is a blocked date

- integration_tests/integration/bookAVisit.cy.ts
- integration_tests/integration/checkYourBooking.cy.ts
- integration_tests/integration/updateAVisit.cy.ts
- server/routes/bookAVisit.ts
- server/routes/visit.ts
- server/routes/visitJourney/checkYourBooking.test.ts
- server/routes/visitJourney/checkYourBooking.ts
- server/routes/visitJourney/mainContact.test.ts
- server/routes/visitJourney/mainContact.ts
Move the call to `/visits/application/{reference}/slot/change` that updates the visit application with accumulated data so that it happens when the 'Main contact' page is submitted instead of the 'Check your answers' page. 
This means that:
* the application is updated as soon as all the required information is available
* the 'Check your details' page now only needs to make a single call (to `/visits/{applicationReference}/book`) so any latency is less likely to result in a user re-trying and ending up making a duplicate request
> VB-3955 Move call to update visit application to earlier in booking journey

- server/routes/visitJourney/dateAndTime.test.ts
- server/views/pages/bookAVisit/dateAndTime.njk
- server/views/pages/bookAVisit/dateAndTime.test.ts
Handle both existing (`DOUBLE_BOOKED`) and forthcoming change to (`DOUBLE_BOOKING_OR_RESERVATION`) value for session conflicts.
`DOUBLE_BOOKED` can be removed once API changes have been released.
> VB-3991 Handle renamed session conflict type

- server/@types/express/index.d.ts
- server/data/orchestrationApiClient.test.ts
- server/data/orchestrationApiClient.ts
- server/routes/blockVisitDates/blockNewDateController.test.ts
- server/routes/blockVisitDates/blockNewDateController.ts
- server/routes/blockVisitDates/blockVisitDatesController.test.ts
- server/routes/blockVisitDates/index.ts
- server/services/visitService.test.ts
- server/services/visitService.ts
- server/views/pages/blockVisitDates/blockNewDate.njk
Render page to block a new visit date (from selected date set in session).
To note:
* actually blocking the date will be in next PR
* date in session will be populated from previous page in journey - being worked on separately
> VB-3742 Block a new date for visits page

- integration_tests/integration/blockDates.cy.ts
- integration_tests/mockApis/orchestration.ts
- server/@types/express/index.d.ts
- server/data/orchestrationApiClient.test.ts
- server/data/orchestrationApiClient.ts
- server/routes/blockVisitDates/blockNewDateController.test.ts
- server/routes/blockVisitDates/blockVisitDatesController.test.ts
- server/routes/blockVisitDates/blockVisitDatesController.ts
- server/routes/blockVisitDates/index.ts
- server/routes/testutils/appSetup.ts
- server/services/blockedDatesService.test.ts
- server/services/blockedDatesService.ts
- server/views/pages/blockVisitDates/blockVisitDates.njk
* Improve listings page (extra options on date picker to hide already-blocked dates; handle no blocked dates)
* 'Wire-up' date picker to POST to the add new block date confirmation page
* Make naming more consistent
(TODO: coming next is the success message when a date is blocked and making the 'unblock' links work)
> VB-3741 Link block visits list page to add new block page

- integration_tests/integration/health.cy.ts
- integration_tests/mockApis/orchestration.ts
- server/middleware/setUpHealthChecks.ts
If there is an error calling the API to get the `activeAgencies` for the `/info` endpoint return an `HTTP 503` response instead of returning normally with `activeAgencies: []`.
Aim is to avoid causing calling services to this endpoint caching incorrect data about the service.
> VB-4397 Respond with 503 on /info endpoint if error retrieving data

- server/services/visitNotificationsService.test.ts
- server/services/visitNotificationsService.ts
- server/views/pages/review/visitsReviewListing.njk
- server/views/pages/visit/summary.njk
Fixes a crash that could occur on the visits review listing page if a visit notification came through from the API with an unexpected type.
In this case now, the raw value of the type is rendered in the review listing and on the booking summary page.
> VB-3894: Handle unexpected notification group event types

- integration_tests/integration/changeEstablishment.cy.ts
- server/@types/bapv.d.ts
- server/@types/express/index.d.ts
- server/data/orchestrationApiClient.test.ts
- server/data/orchestrationApiClient.ts
- server/middleware/populateSelectedEstablishment.test.ts
- server/middleware/populateSelectedEstablishment.ts
- server/middleware/sessionCheckMiddleware.test.ts
- server/routes/changeEstablishment.test.ts
- server/routes/changeEstablishment.ts
- server/routes/testutils/appSetup.ts
- server/routes/testutils/testData.ts
- server/routes/visit.test.ts
- server/routes/visitJourney/selectVisitors.test.ts
- server/routes/visitorUtils.test.ts
- server/routes/visits.test.ts
- server/services/supportedPrisonsService.test.ts
- server/services/supportedPrisonsService.ts
Refactor `getPrisonConfig()` in `SupportedPrisonsService` to be `getPrison()` so all prison config values are available.
Define new `Prison` type to use instead of `PrisonDto` in order to have `prisonId` rather than `code` for consistency.
> VB-4400 Refactor for Prison / PrisonDto

- server/routes/visitJourney/dateAndTime.test.ts
- server/routes/visitJourney/dateAndTime.ts
- server/utils/utils.test.ts
- server/utils/utils.ts
Only display during update journey at end of journey
Fixes raised bug, where a fully booked (not overbooked) session would flag the 'overbooking' page after date and time
> Overbooking feature - update journey - display at end of journey

- integration_tests/e2e/cancelVisit.cy.ts
- integration_tests/e2e/visitDetails.cy.ts
- integration_tests/mockApis/orchestration.ts
- integration_tests/pages/visitCancelled.ts
- server/@types/orchestration-api.d.ts
- server/data/orchestrationApiClient.test.ts
- server/routes/visit.test.ts
- server/routes/visit.ts
- server/services/visitService.test.ts
- server/views/pages/visit/cancelConfirmation.njk
- server/views/pages/visit/summary.njk
Change logic surrounding how the visit history tab gets the 'visit notes' - as booker cancellations don't have notes
Make booker lead cancellations displayed 'cancelled by the visitor' with no reason
> VB-4787, deal with booker lead visit cancellation

- assets/js/components/expandableComment.js
- assets/sass/application.scss
- assets/sass/components/_expandableComment.scss
- server/utils/nunjucksSetup.test.ts
- server/utils/nunjucksSetup.ts
- server/views/components/expandableComment/expandableComment.test.ts
- server/views/components/expandableComment/macro.njk
- server/views/components/expandableComment/template.njk
- server/views/pages/bookAVisit/visitors.njk
Add a component to show a block of text (e.g. text comments on a prisoner alert) up to its **first newline character**. 
A link-styled button to see the full comment is rendered:
When the full comment is shown, there is a link-styled button to hide the full comment.
To use the component, call the macro. E.g. to use this when rendering a table cell:
```
{
html: bapvExpandableComment({ text: alert.comment }),
attributes: { "data-test": "tab-alerts-comment" }
},
```
Also necessary to add the JavaScript include to the appropriate page template at the bottom, e.g.:
```
{% block pageScripts %}
<script src="/assets/components/expandableComment.js"></script>
{% endblock %}
```
Show/hide functionality could be tested in Cypress integration tests.
> VB-4957 Add expandable comment component

- integration_tests/e2e/visitsByDate.cy.ts
- server/@types/bapv.d.ts
- server/routes/visitsByDate.test.ts
- server/routes/visitsByDate.ts
- server/routes/visitsUtils.test.ts
- server/routes/visitsUtils.ts
- server/views/pages/visitsByDate/visitsByDate.njk
- server/views/pages/visitsByDate/visitsByDate.test.ts
Group visit sessions by visit room name instead of Open/Closed sessions.
(Some tests skipped and various `TODO`s to be addressed in follow-on PRs...)
> VB-4974 Visits by date left-hand nav - group sessions by visit room name

- server/data/orchestrationApiClient.test.ts
- server/data/orchestrationApiClient.ts
- server/routes/visitsByDate.test.ts
- server/routes/visitsByDate.ts
- server/routes/visitsUtils.test.ts
- server/routes/visitsUtils.ts
- server/services/visitService.test.ts
- server/services/visitService.ts
- server/views/pages/visitsByDate/visitsByDate.njk
- server/views/pages/visitsByDate/visitsByDate.test.ts
* Show both open and closed sections for a given selected session template (unless capacity is zero)
* Handle `UNKNOWN` (labelled 'All') visits
> VB-4976 Show open and closed visits on the same page

- assets/sass/local.scss
- server/routes/visitsUtils.test.ts
- server/routes/visitsUtils.ts
* Make session side nav headings black text
* If there are multiple visit rooms, order the side nav sections alphabetically by the room names
> VB-4974 Session side nav tweaks

- integration_tests/e2e/reviewVisitsList.cy.ts
- server/config.ts
- server/constants/notificationEvents.ts
- server/data/orchestrationApiClient.test.ts
- server/data/orchestrationApiClient.ts
Add config to filter visit review notifications to an allowed set of values. This means that additional events enabled in production, for example, won't necessarily come through on the front-end unless they are an allowed type.
> VB-4942 Filter visit notification events by configurable allow list

- integration_tests/e2e/reviewAVisit.cy.ts
- integration_tests/e2e/visitDetails.cy.ts
- server/data/orchestrationApiClient.test.ts
- server/data/orchestrationApiClient.ts
- server/routes/testutils/testData.ts
- server/routes/visit/visitDetailsController.test.ts
filter notifications on `getVisitNotifications` - so the `Visit details` page won't display them
(they're already hidden on `Needs review` page)
> VB-5149, filter notifications on visit details page

- server/data/orchestrationApiClient.test.ts
- server/data/orchestrationApiClient.ts
Filter the items returned from the API for a visit's events audit to only include notification event types that are enabled.
> VB-5149 Filter notification types allowed on visit history

- assets/sass/application.scss
- assets/sass/components/_bapv_headings.scss
- assets/sass/local.scss
- server/views/pages/visit/visitDetails.njk
Add `bapv-heading` class to customise padding/margin when used with `govuk-heading-(l|m|s)` styles.
> VB-5042 Add custom heading styles

- server/routes/visit.ts
- server/routes/visit/visitDetailsController.test.ts
- server/services/visitService.test.ts
- server/services/visitService.ts
- server/utils/utils.test.ts
- server/utils/utils.ts
- server/views/pages/visit/visitDetails.njk
* Minor tweaks to Visit details page.
* Add generic `sortItemsByDateAsc()` function to sort an array of any type of item by a specified field that contains a date string. Sorts by date ascending with invalid or missing values at the end.
* Use this to sort the listing of prisoner alerts/restrictions on Select visitors and Visit details pages.
> VB-5293 Visit details page tweaks and sort prisoner alerts/restrictions by date

- server/@types/bapv.d.ts
- server/routes/prisoner.test.ts
- server/routes/prisoner.ts
- server/routes/visit.test.ts
- server/routes/visit.ts
- server/routes/visitJourney/selectVisitors.test.ts
- server/routes/visitJourney/selectVisitors.ts
- server/services/prisonerProfileService.test.ts
- server/services/prisonerProfileService.ts
- server/services/visitService.test.ts
- server/views/pages/bookAVisit/visitors.njk
- server/views/pages/prisoner/profile.njk
* Use same date sort order for prisoner alerts on profile page as is used on visit details page (expiring soonest first)
* Remove unnecessary filter for `active | inactive` alerts (API does this)
* Rename `activeAlerts` to `alerts` for simplicity and consistency with restrictions
> VB-4411 Sort alerts on prisoner profile page by date

- integration_tests/e2e/visitDetails.cy.ts
- server/routes/visit/visitDetailsController.test.ts
- server/views/pages/visit/visitDetails.njk
For prisoner alerts on Visit details page, use `alertCodeDescription` instead of `alertTypeDescription` in order to match what is displayed on Select visitor page.
> VB-5293 Fix prisoner alert descriptions

- server/data/orchestrationApiClient.test.ts
- server/data/orchestrationApiClient.ts
- server/routes/visit/visitDetailsController.test.ts
- server/utils/nunjucksSetup.ts
- server/views/pages/visit/visitDetails.njk
The way the feature flag to hide prisoner alerts/restrictions on visit details page was implemented prevented these being passed through to the update journey.
Change to just hide the alerts/restrictions in the visit details page template, based on the feature flag.
> VB-5364 Fix prisoner alerts/restrictions on update journey

- server/data/orchestrationApiClient.ts
On a booking journey, if an application is changed **before** a main contact is selected (e.g. by going back in journey) `mainContact` will be `undefined`. Fix to handle this.
> VB-5454 Fix for potentially undefined main contact

- integration_tests/pages/visitCancelled.ts
- server/@types/bapv.d.ts
- server/@types/express/index.d.ts
- server/routes/testutils/appSetup.ts
- server/routes/visit/cancelVisitController.test.ts
- server/routes/visit/cancelVisitController.ts
- server/routes/visitorUtils.test.ts
- server/routes/visitorUtils.ts
- server/views/pages/visit/cancelConfirmation.njk
* Use `req.session` instead of `req.flash` for storing data so it won't fail if page refreshed
* Update links from `/` to `/back-to-start` (which incorporates clearing session between journeys)
* Handle visiting cancellation confirmation page when no appropriate session data set
> Improve cancellation confirmation page

- integration_tests/e2e/cancelVisit.cy.ts
- integration_tests/e2e/reviewAVisit.cy.ts
- integration_tests/e2e/reviewVisitsList.cy.ts
- integration_tests/e2e/searchForABooking.cy.ts
- integration_tests/e2e/updateAVisit.cy.ts
- integration_tests/e2e/visitDetails.cy.ts
- integration_tests/mockApis/orchestration.ts
- server/config.ts
- server/constants/eventAudit.ts
- server/data/orchestrationApiClient.test.ts
- server/data/orchestrationApiClient.ts
- server/data/orchestrationApiTypes.ts
- server/routes/testutils/testData.ts
- server/routes/visit/updateVisitController.test.ts
- server/routes/visit/visitDetailsController.test.ts
- server/routes/visit/visitEventsTimelineBuilder.ts
- server/routes/visit/visitUtils.test.ts
- server/routes/visit/visitUtils.ts
- server/services/visitNotificationsService.test.ts
- server/services/visitService.test.ts
- server/services/visitService.ts
The API returns notifications (e.g. `PRISONER_RELEASED`) and audit events (these include notification types and others like `CANCELLED`).
Most of these events have a one-to-one mapping to labels and functionality on the front-end. Visitor restrictions though can be local or global (`PERSON_RESTRICTION_UPSERTED_EVENT`, `VISITOR_RESTRICTION_UPSERTED_EVENT`) but these effectively have to be labelled and treated the same - as a `Visitor restriction`.
This change makes a distinction for events/notifications between raw data/types returned from the API and data/types for use in the application. In the data layer, the two visitor restriction types are converted to a custom value: `VISITOR_RESTRICTION`.
This means that:
* API can remain unchanged - so the distinction is maintained for future use …
> VB-3758 Process raw API event and notification types

- integration_tests/e2e/reviewVisitsList.cy.ts
- integration_tests/mockApis/orchestration.ts
- integration_tests/pages/visitsReviewListing.ts
- server/@types/bapv.d.ts
- server/@types/orchestration-api.d.ts
- server/data/orchestrationApiClient.test.ts
- server/data/orchestrationApiClient.ts
- server/data/orchestrationApiTypes.ts
- server/routes/review/reviewUtils.test.ts
- server/routes/review/reviewUtils.ts
- server/routes/review/visitsReviewListingController.test.ts
- server/routes/review/visitsReviewListingController.ts
- server/routes/testutils/testData.ts
- server/services/visitNotificationsService.test.ts
- server/services/visitNotificationsService.ts
- server/views/pages/review/visitsReviewListing.njk
Rewrite of 'Needs review' visit listing page:
*  use new API that groups by visit, with potentially multiple notifications per visit (previously, a single visit with two notifications would mean two rows)
* reduplicates notification types within a visit row so only one of each type is shown
(Some tidying to do in a follow-on PR to remove now-redundant code for handling the old API and data format.)
> VB-5569 Needs review page: group by visit

- assets/sass/local.scss
- server/routes/visit/updateVisitController.test.ts
- server/routes/visit/updateVisitController.ts
- server/views/pages/review/visitsReviewListing.njk
Follow on from #1053.
* Align 'Confirm update' prompt page with minimum booking window
* (plus an unrelated table styling fix)
> VB-5790 Confirm update prompt: align with minimum booking window

- integration_tests/e2e/visit/visitDetails.cy.ts
- server/@types/orchestration-api.d.ts
- server/constants/eventAudit.ts
- server/data/orchestrationApiClient.ts
- server/routes/visit/visitEventsTimelineBuilder.test.ts
- server/routes/visit/visitEventsTimelineBuilder.ts
- server/routes/visit/visitUtils.test.ts
- server/routes/visit/visitUtils.ts
Visit details page:
* Show 'Approved' and 'Rejected' entries on timeline for visit requests
* For rejected visit requests, show a 'Request rejected' alert message at the top
> VB-5785, VB-5818, VB-5819 Add request action (approve/reject) to timeline and rejected message
